module core {
    interface [LegacyParent=KJS::DOMNode] DocumentType : Node {
        readonly attribute DOMString name;
        readonly attribute NamedNodeMap entities;
        readonly attribute NamedNodeMap notations;
        
        readonly attribute [ConvertNullStringTo=Null] DOMString publicId;
        readonly attribute [ConvertNullStringTo=Null] DOMString systemId;
        readonly attribute [ConvertNullStringTo=Null] DOMString internalSubset;        
    };
}
