module events {
    interface [LegacyParent=KJS::DOMEvent] MutationEvent : Event {
        const unsigned short MODIFICATION = 1;
        const unsigned short ADDITION     = 2;
        const unsigned short REMOVAL      = 3;
        
        readonly attribute Node           relatedNode;
        readonly attribute DOMString      prevValue;
        readonly attribute DOMString      newValue;
        readonly attribute DOMString      attrName;
        readonly attribute unsigned short attrChange;
        
        void initMutationEvent(in AtomicString typeArg, 
                               in boolean canBubbleArg, 
                               in boolean cancelableArg, 
                               in Node relatedNodeArg, 
                               in DOMString prevValueArg, 
                               in DOMString newValueArg, 
                               in DOMString attrNameArg, 
                               in unsigned short attrChangeArg);
    };
}
