#!/usr/bin/perl -w

# Copyright (C) 2005 Apple Computer, Inc.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer. 
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution. 
# 3.  Neither the name of Apple Computer, Inc. ("Apple") nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission. 
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Simplified "run" script for Web Kit Open Source Project.

use strict;
use Getopt::Long;
use FindBin;
use lib $FindBin::Bin;
use webkitdirs;

my $debug = 0;
GetOptions("debug!" => \$debug);

my $productDir = productDir();

# Check to see that Safari is in the usual place.
my $safariPath = "/Applications/Safari.app/Contents/MacOS/Safari";
if (! -x $safariPath) {
    die "Can't find executable at $safariPath.\n";
}

# Search for build products; first test Xcode 2.0 location, then Xcode 2.1 locations.
# For Xcode 2.1, prefer Deployment if both directories are present.
my @testDirs;
if ($debug) {
    @testDirs = ("$productDir", "$productDir/Deployment", "$productDir/Development");
} else {
    @testDirs = ("$productDir", "$productDir/Development", "$productDir/Deployment");
}
my $found = 0;
for my $testDir (@testDirs) {
    next if !-x "$testDir/JavaScriptCore.framework/Versions/A/JavaScriptCore";
    next if !-x "$testDir/WebCore.framework/Versions/A/WebCore";
    next if !-x "$testDir/WebKit.framework/Versions/A/WebKit";
    $productDir = $testDir;
    $found = 1;
    last;
}
if (!$found) {
    die "Could not locate frameworks.\n";
}

# Set up DYLD_FRAMEWORK_PATH to point to the product directory.
print "Start Safari with DYLD_FRAMEWORK_PATH set to point to built WebKit in $productDir.\n";
$ENV{DYLD_FRAMEWORK_PATH} = $productDir;
exec $safariPath or die;
