/*
 * Copyright (c) 2004 World Wide Web Consortium,
 *
 * (Massachusetts Institute of Technology, European Research Consortium for
 * Informatics and Mathematics, Keio University). All Rights Reserved. This
 * work is distributed under the W3C(r) Software License [1] in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
 */

module core
{
	interface CharacterData : Node {
		attribute DOMString data [raises(DOMException)];
		readonly attribute unsigned long length;

		DOMString substringData(in unsigned long offset,
								in unsigned long count)
								[raises(DOMException)];

		void appendData(in DOMString arg)
						[raises(DOMException)];

		void insertData(in unsigned long offset,
						in DOMString arg)
						[raises(DOMException)];

		void deleteData(in unsigned long offset,
						in unsigned long count)
						[raises(DOMException)];

		void replaceData(in unsigned long offset,
						 in unsigned long count,
						 in DOMString arg)
						 [raises(DOMException)];
	};
};
