/*
 * Copyright (c) 2004 World Wide Web Consortium,
 *
 * (Massachusetts Institute of Technology, European Research Consortium for
 * Informatics and Mathematics, Keio University). All Rights Reserved. This
 * work is distributed under the W3C(r) Software License [1] in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
 */

module core
{
	// Introduced in DOM Level 3:
	interface TypeInfo {
		readonly attribute DOMString typeName;
		readonly attribute DOMString typeNamespace;

		// Derivation methods
		const unsigned long DERIVATION_RESTRICTION	= 0x00000001;
		const unsigned long DERIVATION_EXTENSION	= 0x00000002;
		const unsigned long DERIVATION_UNION		= 0x00000004;
		const unsigned long DERIVATION_LIST			= 0x00000008;

		boolean isDerivedFrom(in DOMString typeNamespaceArg,
							  in DOMString typeNameArg,
							  in unsigned long derivationMethod);
	};
};
