/*
    Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies)

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

[
    GenerateIsReachable=ReachableFromDOMWindow,
    JSCustomMarkFunction,
] interface Navigator {
    // FIXME: This is specified to be in it's own mixin called NavigatorCookies.
    // https://html.spec.whatwg.org/multipage/system-state.html#navigatorcookies
    readonly attribute boolean cookieEnabled;

    [Conditional=NAVIGATOR_STANDALONE] readonly attribute boolean standalone;

    undefined getStorageUpdates(); // FIXME: Remove this method or rename to yieldForStorageUpdates.
};

Navigator includes NavigatorID;
Navigator includes NavigatorLanguage;
Navigator includes NavigatorMaxTouchPoints;
Navigator includes NavigatorOnLine;
Navigator includes NavigatorPlugins;
Navigator includes NavigatorServiceWorker;
Navigator includes NavigatorShare;
