[
    ActiveDOMObject,
    Exposed=Window
] interface ShadowRealm : EventTarget {

    undefined terminate();

    [CallWith=GlobalObject] undefined postMessage(any message, sequence<object> transfer);
    [CallWith=GlobalObject] undefined postMessage(any message, optional StructuredSerializeOptions options);
    attribute EventHandler onmessage;
};

ShadowRealm includes ShadowRealmGlobalScope;
