/*
 * Copyright (C) 2026 Apple Inc. All rights reserved.
 */

dictionary TaskControllerInit {
    TaskPriority priority = "user-visible";
};

[
    Exposed=(Window,Worker),
    EnabledBySetting=PrioritizedTaskSchedulingEnabled
] interface TaskController : AbortController {
    [CallWith=CurrentScriptExecutionContext] constructor(optional TaskControllerInit init = {});
    undefined setPriority(TaskPriority priority);
};
