/*
 * Copyright (C) 2017 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

[
    SkipVTableValidation,
    EnabledAtRuntime=AccessibilityObjectModel,
] interface AccessibleNode {
    attribute AccessibleNode? activeDescendant;
    attribute boolean? atomic;
    attribute DOMString? autocomplete;
    attribute boolean? busy;
    attribute DOMString? checked;
    attribute long? colCount;
    attribute unsigned long? colIndex;
    attribute unsigned long? colSpan;
    attribute DOMString? current;
    attribute AccessibleNode? details;
    attribute boolean? disabled;
    attribute AccessibleNode? errorMessage;
    attribute boolean? expanded;
    attribute DOMString? hasPopUp;
    attribute boolean? hidden;
    attribute DOMString? invalid;
    attribute DOMString? keyShortcuts;
    attribute DOMString? label;
    attribute unsigned long? level;
    attribute DOMString? live;
    attribute boolean? modal;
    attribute boolean? multiline;
    attribute boolean? multiselectable;
    attribute DOMString? orientation;
    attribute DOMString? placeholder;
    attribute unsigned long? posInSet;
    attribute DOMString? pressed;
    attribute boolean? readOnly;
    attribute DOMString? relevant;
    attribute boolean? required;
    attribute DOMString? role;
    attribute DOMString? roleDescription;
    attribute long? rowCount;
    attribute unsigned long? rowIndex;
    attribute unsigned long? rowSpan;
    attribute boolean? selected;
    attribute long? setSize;
    attribute DOMString? sort;
    attribute double? valueMax;
    attribute double? valueMin;
    attribute double? valueNow;
    attribute DOMString? valueText;
};
