/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#pragma once

#include "IDLTypes.h"
#include "JSCallbackData.h"
#include "TestCallbackWithFunctionOrDict.h"
#include <wtf/Forward.h>
#include <wtf/TypeCasts.h>

namespace WebCore {

class JSTestCallbackWithFunctionOrDict final : public TestCallbackWithFunctionOrDict {
public:
    static Ref<JSTestCallbackWithFunctionOrDict> create(JSC::JSObject* callback, JSDOMGlobalObject* globalObject)
    {
        return adoptRef(*new JSTestCallbackWithFunctionOrDict(callback, globalObject));
    }

    ScriptExecutionContext* scriptExecutionContext() const;

    ~JSTestCallbackWithFunctionOrDict() final;
    JSCallbackData* callbackData() { return m_data; }

    // Functions
    CallbackResult<typename IDLUndefined::CallbackReturnType> invoke(typename IDLUnion<IDLDictionary<TestDictionary>, IDLCallbackFunction<JSTestCallbackFunction>>::ParameterType callback) override;
    CallbackResult<typename IDLUndefined::CallbackReturnType> invokeRethrowingException(typename IDLUnion<IDLDictionary<TestDictionary>, IDLCallbackFunction<JSTestCallbackFunction>>::ParameterType callback) override;

private:
    JSTestCallbackWithFunctionOrDict(JSC::JSObject*, JSDOMGlobalObject*);

    bool hasCallback() const final { return m_data && m_data->callback(); }

    bool isJSTestCallbackWithFunctionOrDict() const final { return true; }

    void visitJSFunction(JSC::AbstractSlotVisitor&) override;

    void visitJSFunction(JSC::SlotVisitor&) override;

    JSCallbackData* m_data;
};

JSC::JSValue toJS(TestCallbackWithFunctionOrDict&);
inline JSC::JSValue toJS(TestCallbackWithFunctionOrDict* impl) { return impl ? toJS(*impl) : JSC::jsNull(); }

template<> struct JSDOMCallbackConverterTraits<JSTestCallbackWithFunctionOrDict> {
    using Base = TestCallbackWithFunctionOrDict;
};
} // namespace WebCore

SPECIALIZE_TYPE_TRAITS_BEGIN(WebCore::JSTestCallbackWithFunctionOrDict)
    static bool isType(const WebCore::TestCallbackWithFunctionOrDict& callback) { return callback.isJSTestCallbackWithFunctionOrDict(); }
SPECIALIZE_TYPE_TRAITS_END()
