/*
 * Copyright (C) 2006 Apple Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module svg {

    interface [Conditional=SVG] SVGPaint : SVGColor {
        // SVGPaintType
        const unsigned short SVG_PAINTTYPE_UNKNOWN               = 0;
        const unsigned short SVG_PAINTTYPE_RGBCOLOR              = 1;
        const unsigned short SVG_PAINTTYPE_RGBCOLOR_ICCCOLOR     = 2;
        const unsigned short SVG_PAINTTYPE_NONE                  = 101;
        const unsigned short SVG_PAINTTYPE_CURRENTCOLOR          = 102;
        const unsigned short SVG_PAINTTYPE_URI_NONE              = 103;
        const unsigned short SVG_PAINTTYPE_URI_CURRENTCOLOR      = 104;
        const unsigned short SVG_PAINTTYPE_URI_RGBCOLOR          = 105;
        const unsigned short SVG_PAINTTYPE_URI_RGBCOLOR_ICCCOLOR = 106;
        const unsigned short SVG_PAINTTYPE_URI                   = 107;

        readonly attribute SVGPaintType paintType;
        readonly attribute DOMString uri;

        void setUri(in DOMString uri);
        void setPaint(in SVGPaintType paintType, 
                      in DOMString uri, 
                      in DOMString rgbColor, 
                      in DOMString iccColor)
            raises(SVGException);
    };

}
