/*
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 * Copyright (C) 2006, 2009 Apple Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module svg {

    interface [Conditional=SVG, CustomToJS, Polymorphic] SVGPathSeg {
        // Path Segment Types
        const unsigned short PATHSEG_UNKNOWN                      = 0;
        const unsigned short PATHSEG_CLOSEPATH                    = 1;
        const unsigned short PATHSEG_MOVETO_ABS                   = 2;
        const unsigned short PATHSEG_MOVETO_REL                   = 3;
        const unsigned short PATHSEG_LINETO_ABS                   = 4;
        const unsigned short PATHSEG_LINETO_REL                   = 5;
        const unsigned short PATHSEG_CURVETO_CUBIC_ABS            = 6;
        const unsigned short PATHSEG_CURVETO_CUBIC_REL            = 7;
        const unsigned short PATHSEG_CURVETO_QUADRATIC_ABS        = 8;
        const unsigned short PATHSEG_CURVETO_QUADRATIC_REL        = 9;
        const unsigned short PATHSEG_ARC_ABS                      = 10;
        const unsigned short PATHSEG_ARC_REL                      = 11;
        const unsigned short PATHSEG_LINETO_HORIZONTAL_ABS        = 12;
        const unsigned short PATHSEG_LINETO_HORIZONTAL_REL        = 13;
        const unsigned short PATHSEG_LINETO_VERTICAL_ABS          = 14;
        const unsigned short PATHSEG_LINETO_VERTICAL_REL          = 15;
        const unsigned short PATHSEG_CURVETO_CUBIC_SMOOTH_ABS     = 16;
        const unsigned short PATHSEG_CURVETO_CUBIC_SMOOTH_REL     = 17;
        const unsigned short PATHSEG_CURVETO_QUADRATIC_SMOOTH_ABS = 18;
        const unsigned short PATHSEG_CURVETO_QUADRATIC_SMOOTH_REL = 19;

        readonly attribute unsigned short       pathSegType;
        readonly attribute DOMString            pathSegTypeAsLetter;
    };

}
