/*
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 * Copyright (C) 2006 Apple Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module svg {

    interface [Conditional=SVG] SVGPathElement : SVGElement,
                                                 SVGTests,
                                                 SVGLangSpace,
                                                 SVGExternalResourcesRequired,
                                                 SVGStylable,
                                                 SVGTransformable,
                                                 SVGAnimatedPathData {
        readonly attribute SVGAnimatedNumber pathLength;

        float getTotalLength();
        SVGPoint getPointAtLength(in float distance);
        unsigned long getPathSegAtLength(in float distance)
            raises(DOMException, SVGException);

        SVGPathSegClosePath createSVGPathSegClosePath();

        SVGPathSegMovetoAbs createSVGPathSegMovetoAbs(in float x, 
                                                      in float y);
        SVGPathSegMovetoRel createSVGPathSegMovetoRel(in float x, 
                                                      in float y);

        SVGPathSegLinetoAbs createSVGPathSegLinetoAbs(in float x, 
                                                      in float y);
        SVGPathSegLinetoRel createSVGPathSegLinetoRel(in float x, 
                                                      in float y);

        SVGPathSegCurvetoCubicAbs createSVGPathSegCurvetoCubicAbs(in float x, 
                                                                  in float y, 
                                                                  in float x1, 
                                                                  in float y1, 
                                                                  in float x2, 
                                                                  in float y2);
        SVGPathSegCurvetoCubicRel createSVGPathSegCurvetoCubicRel(in float x, 
                                                                  in float y, 
                                                                  in float x1, 
                                                                  in float y1, 
                                                                  in float x2, 
                                                                  in float y2);

        SVGPathSegCurvetoQuadraticAbs createSVGPathSegCurvetoQuadraticAbs(in float x, 
                                                                          in float y, 
                                                                          in float x1, 
                                                                          in float y1);
        SVGPathSegCurvetoQuadraticRel createSVGPathSegCurvetoQuadraticRel(in float x, 
                                                                          in float y, 
                                                                          in float x1, 
                                                                          in float y1);

        SVGPathSegArcAbs createSVGPathSegArcAbs(in float x, 
                                                in float y, 
                                                in float r1, 
                                                in float r2, 
                                                in float angle, 
                                                in boolean largeArcFlag, 
                                                in boolean sweepFlag);
        SVGPathSegArcRel createSVGPathSegArcRel(in float x, 
                                                in float y, 
                                                in float r1, 
                                                in float r2, 
                                                in float angle, 
                                                in boolean largeArcFlag, 
                                                in boolean sweepFlag);

        SVGPathSegLinetoHorizontalAbs createSVGPathSegLinetoHorizontalAbs(in float x);
        SVGPathSegLinetoHorizontalRel createSVGPathSegLinetoHorizontalRel(in float x);

        SVGPathSegLinetoVerticalAbs createSVGPathSegLinetoVerticalAbs(in float y);
        SVGPathSegLinetoVerticalRel createSVGPathSegLinetoVerticalRel(in float y);

        SVGPathSegCurvetoCubicSmoothAbs createSVGPathSegCurvetoCubicSmoothAbs(in float x, 
                                                                              in float y, 
                                                                              in float x2, 
                                                                              in float y2);
        SVGPathSegCurvetoCubicSmoothRel createSVGPathSegCurvetoCubicSmoothRel(in float x, 
                                                                              in float y, 
                                                                              in float x2, 
                                                                              in float y2);

        SVGPathSegCurvetoQuadraticSmoothAbs createSVGPathSegCurvetoQuadraticSmoothAbs(in float x, 
                                                                                      in float y);
        SVGPathSegCurvetoQuadraticSmoothRel createSVGPathSegCurvetoQuadraticSmoothRel(in float x, 
                                                                                      in float y);
    };

}
