/*
 * Copyright (C) 2007 Nikolas Zimmermann <zimmermann@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module svg {

    interface [Conditional=SVG] SVGTextPathElement : SVGTextContentElement,
                                                     SVGURIReference {    
        // textPath Method Types
        const unsigned short TEXTPATH_METHODTYPE_UNKNOWN   = 0;
        const unsigned short TEXTPATH_METHODTYPE_ALIGN     = 1;
        const unsigned short TEXTPATH_METHODTYPE_STRETCH   = 2;

        // textPath Spacing Types
        const unsigned short TEXTPATH_SPACINGTYPE_UNKNOWN  = 0;
        const unsigned short TEXTPATH_SPACINGTYPE_AUTO     = 1;
        const unsigned short TEXTPATH_SPACINGTYPE_EXACT    = 2;

        readonly attribute SVGAnimatedLength startOffset;
        readonly attribute SVGAnimatedEnumeration method;
        readonly attribute SVGAnimatedEnumeration spacing;
    };

}
