INCLUDE(FindPkgConfig)

PKG_CHECK_MODULES (EDJE REQUIRED edje>=1.0.0)
PKG_CHECK_MODULES (ECORE REQUIRED ecore>=1.0.0)
PKG_CHECK_MODULES (ECORE_EVAS REQUIRED ecore-evas>=1.0.0)
PKG_CHECK_MODULES (EFLDEPS REQUIRED
  eina>=1.0.0
  evas>=1.0.0
  ecore>=1.0.0
  ecore-file>=1.0.0
  ecore-evas>=1.0.0
  edje>=1.0.0)
PKG_CHECK_MODULES (EINA REQUIRED eina>=1.0.0)
PKG_CHECK_MODULES (ECORE_X ecore-x>=1.0.0)
PKG_CHECK_MODULES (EVAS REQUIRED evas>=1.0.0)

