# Features that PlatformEnableCocoa.h derives from the SDK, shared by the Cocoa
# ports. Include this between WEBKIT_OPTION_BEGIN() and WEBKIT_OPTION_END(); the
# rest of the Cocoa configuration lives in OptionsCocoa, which runs later.
WEBKIT_OPTION_OWNED_BY_PLATFORM_H(
    ENABLE_APPLE_PAY_AUTOMATIC_RELOAD_LINE_ITEM
    ENABLE_APPLE_PAY_AUTOMATIC_RELOAD_PAYMENTS
    ENABLE_APPLE_PAY_COUPON_CODE
    ENABLE_APPLE_PAY_DEFERRED_LINE_ITEM
    ENABLE_APPLE_PAY_DEFERRED_PAYMENTS
    ENABLE_APPLE_PAY_DELEGATED_REQUEST
    ENABLE_APPLE_PAY_DISBURSEMENTS
    ENABLE_APPLE_PAY_INSTALLMENTS
    ENABLE_APPLE_PAY_LATER_AVAILABILITY
    ENABLE_APPLE_PAY_MERCHANT_CATEGORY_CODE
    ENABLE_APPLE_PAY_MULTI_MERCHANT_PAYMENTS
    ENABLE_APPLE_PAY_PAYMENT_ORDER_DETAILS
    ENABLE_APPLE_PAY_RECURRING_LINE_ITEM
    ENABLE_APPLE_PAY_RECURRING_PAYMENTS
    ENABLE_APPLE_PAY_SELECTED_SHIPPING_METHOD
    ENABLE_APPLE_PAY_SHIPPING_CONTACT_EDITING_MODE
    ENABLE_APPLE_PAY_SHIPPING_METHOD_DATE_COMPONENTS_RANGE
    ENABLE_MEDIA_SOURCE_IN_WORKERS
    ENABLE_PREDEFINED_COLOR_SPACE_DISPLAY_P3
)
