FILE(MAKE_DIRECTORY ${DERIVED_SOURCES_JAVASCRIPTCORE_DIR})
FILE(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/Source/JavaScriptCore/runtime)

IF (ENABLE_WEBCORE)
    FILE(MAKE_DIRECTORY ${DERIVED_SOURCES_WEBCORE_DIR})
ENDIF ()

IF (ENABLE_WEBKIT2)
    FILE(MAKE_DIRECTORY ${DERIVED_SOURCES_WEBKIT2_DIR})
ENDIF ()
