/*
 * Copyright (C) 2006 Apple Computer, Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

module core {

    interface [LegacyParent=KJS::DOMEventTargetNode, GenerateConstructor] Element : EventTargetNode {

        // DOM Level 1 Core

        readonly attribute [ConvertNullStringTo=Null] DOMString tagName;

        [ConvertNullStringTo=Null] DOMString getAttribute(in DOMString name);

        void setAttribute(in DOMString name,
                          in DOMString value)
            raises(DOMException);

        void removeAttribute(in DOMString name)
            raises(DOMException);

        [UsesPassRefPtr] Attr getAttributeNode(in DOMString name);

        [UsesPassRefPtr] Attr setAttributeNode(in Attr newAttr)
            raises(DOMException);

        [UsesPassRefPtr] Attr removeAttributeNode(in Attr oldAttr)
            raises(DOMException);

        [UsesPassRefPtr] NodeList getElementsByTagName(in DOMString name);

        // DOM Level 2 Core

        DOMString getAttributeNS(in [ConvertNullToNullString] DOMString namespaceURI,
                                 in DOMString localName);

        void setAttributeNS(in [ConvertNullToNullString] DOMString namespaceURI,
                            in DOMString qualifiedName, 
                            in DOMString value)
            raises(DOMException);

        void removeAttributeNS(in [ConvertNullToNullString] DOMString namespaceURI,
                               in DOMString localName)
            raises(DOMException);

        [UsesPassRefPtr] NodeList getElementsByTagNameNS(in [ConvertNullToNullString] DOMString namespaceURI,
                                                         in DOMString localName);

        [UsesPassRefPtr] Attr getAttributeNodeNS(in [ConvertNullToNullString] DOMString namespaceURI,
                                                 in DOMString localName);

        [UsesPassRefPtr] Attr setAttributeNodeNS(in Attr newAttr)
            raises(DOMException);

        boolean hasAttribute(in DOMString name);

        boolean hasAttributeNS(in [ConvertNullToNullString] DOMString namespaceURI,
                               in DOMString localName);

        readonly attribute [ObjCCatagory=DOMElementCSSInlineStyle] CSSStyleDeclaration style;

        // Common extensions

        readonly attribute [ObjCCatagory=DOMElementExtensions] long offsetLeft;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long offsetTop;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long offsetWidth;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long offsetHeight;

        readonly attribute [ObjCCatagory=DOMElementExtensions] Element offsetParent;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long clientWidth;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long clientHeight;

        attribute [ObjCCatagory=DOMElementExtensions] long scrollLeft;

        attribute [ObjCCatagory=DOMElementExtensions] long scrollTop;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long scrollWidth;

        readonly attribute [ObjCCatagory=DOMElementExtensions] long scrollHeight;

        void focus();

        void blur();

        [ObjCCatagory=DOMElementExtensions] void scrollIntoView(in [Optional] boolean alignWithTop);

        // IE extensions

        [Exclude=ObjC] Node insertAdjacentElement(in DOMString position, 
                                                  in Node newElement)
            raises(DOMException);

        [Exclude=ObjC] boolean contains(in Element element);

        // WebKit extensions

        [ObjCCatagory=DOMElementExtensions] void scrollIntoViewIfNeeded(in [Optional] boolean centerIfNeeded);

        [Exclude=ObjC] void scrollByLines(in long lines);

        [Exclude=ObjC] void scrollByPages(in long pages);

    };

}
