/*
 * Copyright (C) 2006 Apple Computer, Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module core {

    interface [
        GenerateConstructor,
        InterfaceUUID=5947E8F8-B5CB-4a51-B883-B91F344F1E13,
        ImplementationUUID=7EEC0376-3D76-4643-A964-97B8AC1FB6D3
    ] ProcessingInstruction : Node {

        // DOM Level 1

        readonly attribute [ConvertNullStringTo=Null] DOMString target;
                 attribute [ConvertNullStringTo=Null, ConvertNullToNullString] DOMString data
                     setter raises(DOMException);

#if !defined(LANGUAGE_COM)
        // interface LinkStyle from DOM Level 2 Style Sheets
        readonly attribute StyleSheet sheet;
#endif

    };

}
