module events {

        interface [LegacyParent=KJS::DOMUIEvent] WheelEvent : UIEvent {
                readonly attribute boolean altKey;
                readonly attribute long    clientX;
                readonly attribute long    clientY;
                readonly attribute boolean ctrlKey;
                readonly attribute boolean metaKey;
                readonly attribute boolean shiftKey;
 
                readonly attribute long    wheelDelta;
                readonly attribute long    offsetX;
                readonly attribute long    offsetY;
                readonly attribute long    screenX;
                readonly attribute long    screenY;
                readonly attribute long    x;
                readonly attribute long    y;
        };

}

