#!/usr/bin/env python3

# Copyright (C) 2024 Igalia S.L.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 3.  Neither the name of Apple Inc. ("Apple") nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import annotations
from typing import TypedDict
import sys
import argparse
from pathlib import Path

dir_scripts = Path(__file__).parents[1].joinpath("Scripts")
sys.path.insert(0, str(dir_scripts))

from webkitpy.autoinstalled import yaml


class CandidatesFileData(TypedDict):
    user_managed: bool
    candidates: list[str]


def update_commands_conf(path_example: Path, path_dest: Path):
    with open(path_example, "rb") as f:
        updated_bytes = f.read()
    try:
        with open(path_dest, "rb") as f:
            current_bytes = f.read()
            current_data: CandidatesFileData = yaml.safe_load(current_bytes.decode())
            if current_data["user_managed"] or current_bytes == updated_bytes:
                return
    except FileNotFoundError:
        pass
    # Create or update the file
    with open(path_dest, "wb") as f:
        f.write(updated_bytes)


def main():
    parser = argparse.ArgumentParser("update-compile-commands-conf",
        description="Creates or updates the update-compile-commands-symlink.conf file.")
    parser.add_argument("compile_commands_conf_example", type=Path)
    parser.add_argument("compile_commands_conf_dest", type=Path)
    args = parser.parse_args()
    update_commands_conf(path_example=args.compile_commands_conf_example,
        path_dest=args.compile_commands_conf_dest)


if __name__ == "__main__":
    main()
