application: webkit-test-results
version: 1
runtime: python27
threadsafe: false
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /dashboards
  static_dir: static-dashboards

- url: /testfile/delete
  script: main.py
  login: admin

- url: /.*
  script: main.py
