module svg
{
  interface [Conditional=SVG] SVGAnimationElement : 
                SVGElement,
                SVGTests,
                SVGExternalResourcesRequired {
    readonly attribute SVGElement targetElement;
    float getStartTime (  );
    float getCurrentTime (  );
    float getSimpleDuration (  )
                    raises( DOMException );
  };
};
