module svg
{
  interface [Conditional=SVG] SVGAnimatedInteger { 
             attribute long baseVal;
                         // raises DOMException on setting
    readonly attribute long animVal;
  };
};
