module svg
{
  interface SVGAnimatedEnumeration { 
             attribute unsigned short baseVal;
                         // raises DOMException on setting
    readonly attribute unsigned short animVal;
  };
};
