module svg
{
  interface [Conditional=SVG] SVGAnimatedNumber { 
             attribute float baseVal;
                         // raises DOMException on setting
    readonly attribute float animVal;
  };
};
