module svg
{
  interface [Conditional=SVG] SVGAnimatedBoolean { 
             attribute boolean baseVal;
                         // raises DOMException on setting
    readonly attribute boolean animVal;
  };
};
