module svg
{
  interface [Conditional=SVG] SVGAnimatedString { 
             attribute core::DOMString baseVal;
                         // raises DOMException on setting
    readonly attribute core::DOMString animVal;
  };
};
