module svg
{
  interface [Conditional=SVG] SVGClipPathElement : 
                SVGElement,
                SVGTests,
                SVGLangSpace,
                SVGExternalResourcesRequired,
                SVGStylable,
                SVGTransformable {
             //   SVGUnitTypes { 
    readonly attribute SVGAnimatedEnumeration clipPathUnits;
  };
};
