module svg
{
  interface SVGCursorElement : 
                SVGElement,
                SVGURIReference,
                SVGTests,
                SVGExternalResourcesRequired { 
    readonly attribute SVGAnimatedLength x;
    readonly attribute SVGAnimatedLength y;
  };
};
