module svg
{
  interface SVGColor : css::CSSValue { 
    // Color Types
    const unsigned short SVG_COLORTYPE_UNKNOWN           = 0;
    const unsigned short SVG_COLORTYPE_RGBCOLOR          = 1;
    const unsigned short SVG_COLORTYPE_RGBCOLOR_ICCCOLOR = 2;
    const unsigned short SVG_COLORTYPE_CURRENTCOLOR      = 3;
    readonly attribute unsigned short colorType;
    readonly attribute css::RGBColor  rgbColor;
    //readonly attribute SVGICCColor    iccColor;
    void        setRGBColor ( in core::DOMString rgbColor )
                    raises( SVGException );
    void        setRGBColorICCColor ( in core::DOMString rgbColor, in core::DOMString iccColor )
                    raises( SVGException );
    void        setColor ( in unsigned short colorType, in core::DOMString rgbColor, in core::DOMString iccColor )
                    raises( SVGException );
  };
};
