module svg
{
  interface SVGDocument : 
                core::Document {
    readonly attribute core::DOMString    title;
    readonly attribute core::DOMString     referrer;
    readonly attribute core::DOMString      domain;
    readonly attribute core::DOMString      URL;
    readonly attribute SVGSVGElement rootElement;

	// Overwrite the one in events::DocumentEvent
	events::Event createEvent(in core::DOMString eventType) [raises(core::DOMException)];
  };
};
