module svg
{
  interface SVGElement : core::Element {
// NOTE: using getId because id already in use in NodeImpl
    attribute core::DOMString getId;
                         // raises DOMException on setting
    attribute core::DOMString xmlbase;
                         // raises DOMException on setting
    readonly attribute SVGSVGElement ownerSVGElement;
    readonly attribute SVGElement viewportElement;
  };
};
