module svg
{
  interface [Conditional=SVG] SVGFEFloodElement : 
                SVGElement,
                SVGFilterPrimitiveStandardAttributes { 
    readonly attribute SVGAnimatedString      in1;
  };
};
