module svg
{
  interface [nodptr, Conditional=SVG] SVGFitToViewBox { 
    readonly attribute SVGAnimatedRect                viewBox;
    readonly attribute SVGAnimatedPreserveAspectRatio preserveAspectRatio;
  };
};
