module svg
{
  interface [Conditional=SVG] SVGFEComponentTransferElement : 
                SVGElement,
                SVGFilterPrimitiveStandardAttributes { 
    readonly attribute SVGAnimatedString in1;
  };
};
