module svg
{
  interface [Conditional=SVG] SVGFEOffsetElement : 
                SVGElement,
                SVGFilterPrimitiveStandardAttributes { 
    readonly attribute SVGAnimatedString in1;
    readonly attribute SVGAnimatedNumber dx;
    readonly attribute SVGAnimatedNumber dy;
  };
};
