module svg
{
  interface [Conditional=SVG] SVGICCColor { 
             attribute core::DOMString      colorProfile;
                         // raises DOMException on setting
    readonly attribute SVGNumberList colors;
  };
};
