module svg
{
  interface [Conditional=SVG] SVGPaint : SVGColor { 
    // Paint Types
    const unsigned short SVG_PAINTTYPE_UNKNOWN               = 0;
    const unsigned short SVG_PAINTTYPE_RGBCOLOR              = 1;
    const unsigned short SVG_PAINTTYPE_RGBCOLOR_ICCCOLOR     = 2;
    const unsigned short SVG_PAINTTYPE_NONE                  = 101;
    const unsigned short SVG_PAINTTYPE_CURRENTCOLOR          = 102;
    const unsigned short SVG_PAINTTYPE_URI_NONE              = 103;
    const unsigned short SVG_PAINTTYPE_URI_CURRENTCOLOR      = 104;
    const unsigned short SVG_PAINTTYPE_URI_RGBCOLOR          = 105;
    const unsigned short SVG_PAINTTYPE_URI_RGBCOLOR_ICCCOLOR = 106;
    const unsigned short SVG_PAINTTYPE_URI                   = 107;
    readonly attribute unsigned short paintType;
    readonly attribute core::DOMString      uri;
    void setUri ( in core::DOMString uri );
    void setPaint ( in unsigned short paintType, in core::DOMString uri, in core::DOMString rgbColor, in core::DOMString iccColor )
                    raises( SVGException );
  };
};
