module svg
{
  interface [Conditional=SVG] SVGPathSegLinetoAbs : SVGPathSeg { 
             attribute float   x;
                         // raises DOMException on setting
             attribute float   y;
                         // raises DOMException on setting
  };
  
  interface [Conditional=SVG] SVGPathSegLinetoRel : SVGPathSeg { 
             attribute float   x;
                         // raises DOMException on setting
             attribute float   y;
                         // raises DOMException on setting
  };
};
