module svg
{
  interface [Conditional=SVG] SVGPathSegList { 
    readonly attribute unsigned long numberOfItems;
    void   clear (  )
                    raises( core::DOMException );
    SVGPathSeg initialize ( in SVGPathSeg newItem )
                    raises( core::DOMException, SVGException );
    SVGPathSeg getItem ( in unsigned long index )
                    raises( core::DOMException );
    SVGPathSeg insertItemBefore ( in SVGPathSeg newItem, in unsigned long index )
                    raises( core::DOMException, SVGException );
    SVGPathSeg replaceItem ( in SVGPathSeg newItem, in unsigned long index )
                    raises( core::DOMException, SVGException );
    SVGPathSeg removeItem ( in unsigned long index )
                    raises( core::DOMException );
    SVGPathSeg appendItem ( in SVGPathSeg newItem )
                    raises( core::DOMException, SVGException );
  };
};
