module svg
{
  interface SVGPathSegCurvetoCubicSmoothAbs : SVGPathSeg { 
             attribute float   x;
                         // raises DOMException on setting
             attribute float   y;
                         // raises DOMException on setting
             attribute float   x2;
                         // raises DOMException on setting
             attribute float   y2;
                         // raises DOMException on setting
  };
  
  interface SVGPathSegCurvetoCubicSmoothRel : SVGPathSeg { 
             attribute float   x;
                         // raises DOMException on setting
             attribute float   y;
                         // raises DOMException on setting
             attribute float   x2;
                         // raises DOMException on setting
             attribute float   y2;
                         // raises DOMException on setting
  };
};
