module svg
{
  interface [Conditional=SVG] SVGPathSegLinetoHorizontalAbs : SVGPathSeg { 
             attribute float   x;
                         // raises DOMException on setting
  };
  
  interface [Conditional=SVG] SVGPathSegLinetoHorizontalRel : SVGPathSeg { 
             attribute float   x;
                         // raises DOMException on setting
  };
};
