module svg
{
  interface [Conditional=SVG] SVGPathSegLinetoVerticalAbs : SVGPathSeg { 
             attribute float   y;
                         // raises DOMException on setting
  };

  interface [Conditional=SVG] SVGPathSegLinetoVerticalRel : SVGPathSeg { 
             attribute float   y;
                         // raises DOMException on setting
  };
};
