module svg
{
  interface SVGRect { 
             attribute float x;
                         // raises DOMException on setting
             attribute float y;
                         // raises DOMException on setting
             attribute float width;
                         // raises DOMException on setting
             attribute float height;
                         // raises DOMException on setting
  };
};
