module svg
{
  interface SVGStringList { 
    readonly attribute unsigned long numberOfItems;
    void   clear (  )
                    raises( core::DOMException );
    core::DOMString initialize ( in core::DOMString newItem )
                    raises( core::DOMException, SVGException );
    core::DOMString getItem ( in unsigned long index )
                    raises( core::DOMException );
    core::DOMString insertItemBefore ( in core::DOMString newItem, in unsigned long index )
                    raises( core::DOMException, SVGException );
    core::DOMString replaceItem ( in core::DOMString newItem, in unsigned long index )
                    raises( core::DOMException, SVGException );
    core::DOMString removeItem ( in unsigned long index )
                    raises( core::DOMException );
    core::DOMString appendItem ( in core::DOMString newItem )
                    raises( core::DOMException, SVGException );
  };
};
