module svg
{
  interface SVGViewElement : 
                SVGElement,
                SVGExternalResourcesRequired,
                SVGFitToViewBox,
                SVGZoomAndPan { 
    readonly attribute SVGStringList viewTarget;
  };
};
