module svg
{
  interface [nodptr, Conditional=SVG] SVGZoomAndPan { 
    // Zoom and Pan Types
    const unsigned short SVG_ZOOMANDPAN_UNKNOWN   = 0;
    const unsigned short SVG_ZOOMANDPAN_DISABLE = 1;
    const unsigned short SVG_ZOOMANDPAN_MAGNIFY = 2;
             attribute unsigned short zoomAndPan;
                         // raises DOMException on setting
  };
};
