#define PREFIX "/usr/local"
#define INCLUDE_DIR "/usr/local/include"
#define LIB_DIR "/usr/local/lib"
#define XTRA_LDFLAGS ""
#define XTRA_CPPFLAGS "-D_REENTRANT "
#define XTRA_LIBS "-lz "
#define CFLAGS "-g -O2 -fno-strict-aliasing -fno-optimize-sibling-calls"
#define CPPFLAGS ""
#define LDFLAGS ""
#define LIBS "-lm "
#define SRCDIR "."
#define PREFIX "/usr/local"
#define INCLUDE_DIR "/usr/local/include"
#define LIB_DIR "/usr/local/lib"
#define XTRA_LDFLAGS ""
#define XTRA_CPPFLAGS "-D_REENTRANT "
#define XTRA_LIBS "-lz "
#define CFLAGS "-g -O2 -fno-strict-aliasing -fno-optimize-sibling-calls"
#define CPPFLAGS ""
#define LDFLAGS ""
#define LIBS "-lm "
#define SRCDIR "."
#define PREFIX "/usr/local"
#define INCLUDE_DIR "/usr/local/include"
#define LIB_DIR "/usr/local/lib"
#define XTRA_LDFLAGS ""
#define XTRA_CPPFLAGS "-D_REENTRANT "
#define XTRA_LIBS "-lz "
#define CFLAGS "-g -O2 -fno-strict-aliasing -fno-optimize-sibling-calls"
#define CPPFLAGS ""
#define LDFLAGS ""
#define LIBS "-lm "
#define SRCDIR "."
#define PREFIX "/usr/local"
#define INCLUDE_DIR "/usr/local/include"
#define LIB_DIR "/usr/local/lib"
#define XTRA_LDFLAGS ""
#define XTRA_CPPFLAGS "-D_REENTRANT "
#define XTRA_LIBS "-lz "
#define CFLAGS "-g -O2 -fno-strict-aliasing -fno-optimize-sibling-calls"
#define CPPFLAGS ""
#define LDFLAGS ""
#define LIBS "-lm "
#define SRCDIR "."
