if exist "%CONFIGURATIONBUILDDIR%\buildfailed" del "%CONFIGURATIONBUILDDIR%\buildfailed"

mkdir 2>NUL "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt46.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt46.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt46%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt46%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt44.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt44.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt44%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt44%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\libicuin%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\libicuin%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\libicuuc%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\libicuuc%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt40.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt40.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt40%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt40%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icuin40%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icuin40%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icuuc40%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icuuc40%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt42.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt42.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icudt42%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icudt42%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icuin42%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icuin42%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\icuuc42%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\icuuc42%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\CoreFoundation%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\CoreFoundation%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\CoreFoundation.resources" xcopy /y /d /e /i "%WebKit_Libraries%\bin\CoreFoundation.resources" "%CONFIGURATIONBUILDDIR%\bin\CoreFoundation.resources"
if exist "%WebKit_Libraries%\bin\pthreadVC2%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\pthreadVC2%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\objc%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\objc%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\ASL%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\ASL%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin\libdispatch%LIBRARYCONFIGSUFFIX%.dll" xcopy /y /d "%WebKit_Libraries%\bin\libdispatch%LIBRARYCONFIGSUFFIX%.dll" "%CONFIGURATIONBUILDDIR%\bin"

cmd /c
