if exist "%CONFIGURATIONBUILDDIR%\buildfailed" del "%CONFIGURATIONBUILDDIR%\buildfailed"

mkdir 2>NUL "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt46.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt46.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt46.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt46.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt44.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt44.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt44.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt44.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\libicuin.dll" xcopy /y /d "%WebKit_Libraries%\bin32\libicuin.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\libicuuc.dll" xcopy /y /d "%WebKit_Libraries%\bin32\libicuuc.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt40.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt40.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icuin40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuin40.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icuuc40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuuc40.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt42.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icudt42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt42.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icuin42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuin42.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\icuuc42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuuc42.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\CoreFoundation.dll" xcopy /y /d "%WebKit_Libraries%\bin32\CoreFoundation.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\CoreFoundation.resources" xcopy /y /d /e /i "%WebKit_Libraries%\bin32\CoreFoundation.resources" "%CONFIGURATIONBUILDDIR%\bin\CoreFoundation.resources"
if exist "%WebKit_Libraries%\bin32\pthreadVC2.dll" xcopy /y /d "%WebKit_Libraries%\bin32\pthreadVC2.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\objc.dll" xcopy /y /d "%WebKit_Libraries%\bin32\objc.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\ASL.dll" xcopy /y /d "%WebKit_Libraries%\bin32\ASL.dll" "%CONFIGURATIONBUILDDIR%\bin"
if exist "%WebKit_Libraries%\bin32\libdispatch.dll" xcopy /y /d "%WebKit_Libraries%\bin32\libdispatch.dll" "%CONFIGURATIONBUILDDIR%\bin"

cmd /c
