# Copyright (C) 2020-2023 Apple Inc. All rights reserved.
# Copyright (C) 2021 Igalia S.L.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from . import loadConfig
import os
import unittest


class TestExpectedBuildSteps(unittest.TestCase):

    expected_steps = {
        'Style-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'update-working-directory',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'check-webkit-style'
        ],
        'Apply-WatchList-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'update-working-directory',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'apply-watch-list'
        ],
        'GTK-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'jhbuild',
            'validate-change',
            'clean-derived-sources',
            'compile-webkit',
            'install-built-product'
        ],
        'GTK-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'jhbuild',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'set-build-summary'
        ],
        'iOS-17-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'iOS-17-Simulator-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'iOS-17-Simulator-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'iOS-17-Simulator-WPT-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'macOS-Sequoia-Debug-Build-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'macOS-Sequoia-Debug-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'macOS-Ventura-Release-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'macOS-Ventura-Release-WK1-Tests-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'macOS-Ventura-Release-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'macOS-Ventura-Release-WK2-Intel-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'macOS-Safer-CPP-Checks-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'show-identifier',
            'install-cmake',
            'install-ninja',
            'print-clang-version',
            'checkout-llvm-project',
            'update-clang',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'scan-build'
        ],
        'macOS-Release-WK2-Stress-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'visionOS-2-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'visionOS-2-Simulator-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'visionOS-2-Simulator-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'download-built-product',
            'extract-built-product',
            'wait-for-crash-collection',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'trigger-crash-log-submission',
            'set-build-summary'
        ],
        'watchOS-11-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'watchOS-11-Simulator-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'tvOS-18-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'tvOS-18-Simulator-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'Win-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-webkit'
        ],
        'Win-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'win-deps',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'set-build-summary'
        ],
        'WPE-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'jhbuild',
            'validate-change',
            'clean-derived-sources',
            'compile-webkit'
        ],
        'WPE-Cairo-Build-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'jhbuild',
            'validate-change',
            'clean-derived-sources',
            'compile-webkit'
        ],
        'WPE-WK2-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'get-test-expectations-baseline',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'get-updated-test-expectations',
            'find-modified-layout-tests',
            'jhbuild',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-layout-tests-in-stress-mode',
            'layout-tests',
            'set-build-summary'
        ],
        'JSC-Tests-arm64-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-jsc',
            'jscore-test'
        ],
        'JSC-Tests-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-jsc',
            'jscore-test'
        ],
        'JSC-ARMv7-32bits-Build-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'kill-old-processes',
            'validate-change',
            'compile-jsc'
        ],
        'JSC-ARMv7-32bits-Tests-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'jscore-test'
        ],
        'Bindings-Tests-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'validate-change',
            'bindings-tests'
        ],
        'WebKitPy-Tests-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'validate-change',
            'webkitpy-tests',
            'set-build-summary'
        ],
        'WebKitPerl-Tests-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'validate-change',
            'webkitperl-tests'
        ],
        'API-Tests-iOS-Simulator-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-api-tests',
            'set-build-summary'
        ],
        'API-Tests-macOS-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-api-tests',
            'set-build-summary'
        ],
        'API-Tests-GTK-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'jhbuild',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-api-tests',
            'set-build-summary'
        ],
        'API-Tests-WPE-EWS': [
            'configure-build',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'jhbuild',
            'download-built-product',
            'extract-built-product',
            'kill-old-processes',
            'run-api-tests',
            'set-build-summary'
        ],
        'Services-EWS': [
            'configure-build',
            'check-change-relevance',
            'validate-change',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'checkout-specific-revision',
            'show-identifier',
            'apply-patch',
            'checkout-pull-request',
            'validate-change',
            'build-webkit-org-unit-tests',
            'buildbot-check-config-for-build-webkit',
            'ews-unit-tests',
            'buildbot-check-config-for-ews',
            'resultsdbpy-unit-tests'
        ],
        'Commit-Queue': [
            'configure-build',
            'validate-change',
            'validate-committer-and-reviewer',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'update-working-directory',
            'show-identifier',
            'install-hooks',
            'apply-patch',
            'validate-squashed',
            'add-reviewer-to-commit-message',
            'validate-commit-message',
            'kill-old-processes',
            'compile-webkit',
            'kill-old-processes',
            'validate-change',
            'check-status-on-other-ewses',
            'layout-tests',
            'validate-change',
            'canonicalize-commit',
            'push-commit-to-webkit-repo',
            'set-build-summary'
        ],
        'Merge-Queue': [
            'configure-build',
            'validate-change',
            'determine-label-owner',
            'validate-committer-and-reviewer',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'map-branch-alias',
            'update-working-directory',
            'show-identifier',
            'install-hooks',
            'checkout-pull-request',
            'validate-remote',
            'validate-squashed',
            'add-reviewer-to-commit-message',
            'validate-commit-message',
            'kill-old-processes',
            'compile-webkit',
            'kill-old-processes',
            'validate-change',
            'check-status-on-other-ewses',
            'layout-tests',
            'validate-change',
            'canonicalize-commit',
            'push-pull-request-branch',
            'update-pull-request',
            'push-commit-to-webkit-repo',
            'set-build-summary'
        ],
        'Unsafe-Merge-Queue': [
            'configure-build',
            'validate-change',
            'determine-label-owner',
            'validate-committer-and-reviewer',
            'configuration',
            'clean-up-git-repo',
            'checkout-source',
            'fetch-branch-references',
            'map-branch-alias',
            'update-working-directory',
            'show-identifier',
            'install-hooks',
            'checkout-pull-request',
            'validate-remote',
            'validate-squashed',
            'add-reviewer-to-commit-message',
            'validate-commit-message',
            'canonicalize-commit',
            'validate-change',
            'push-pull-request-branch',
            'update-pull-request',
            'push-commit-to-webkit-repo',
            'set-build-summary'
        ],
        'Safe-Merge-Queue': [
            'retrieve-pr-data-from-label',
            'retrieve-pr-data-from-label',
            'retrieve-pr-data-from-label'
        ],
    }

    def setUp(self):
        cwd = os.path.dirname(os.path.abspath(__file__))
        self.config = {}
        loadConfig.loadBuilderConfig(self.config, is_test_mode_enabled=True, master_prefix_path=cwd)

    def test_all_expected_steps(self):
        self.maxDiff = None
        for builder in self.config['builders']:
            buildSteps = []
            for step in builder['factory'].steps:
                buildSteps.append(step.factory.name)
            self.assertTrue(builder['name'] in self.expected_steps, 'Missing expected steps for builder: %s\n Actual result is %s' % (builder['name'], buildSteps))
            self.assertListEqual(self.expected_steps[builder['name']], buildSteps, msg="Expected steps don't match for builder %s" % builder['name'])

    def test_unnecessary_expected_steps(self):
        builders = set()
        for builder in self.config['builders']:
            builders.add(builder['name'])
        for builder in self.expected_steps:
            self.assertTrue(builder in builders, "Builder %s doesn't exist, but has unnecessary expected steps" % builder)
