if exist "%CONFIGURATIONBUILDDIR%\buildfailed" del "%CONFIGURATIONBUILDDIR%\buildfailed"

mkdir 2>NUL "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt46.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt46.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt46.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt46.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt44.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt44.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt44.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt44.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\libicuin%DebugSuffix%.dll" xcopy /y /d "%WebKit_Libraries%\bin32\libicuin%DebugSuffix%.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\libicuuc%DebugSuffix%.dll" xcopy /y /d "%WebKit_Libraries%\bin32\libicuuc%DebugSuffix%.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt40.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt40.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icuin40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuin40.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icuuc40.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuuc40.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt42.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icudt42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icudt42.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icuin42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuin42.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\icuuc42.dll" xcopy /y /d "%WebKit_Libraries%\bin32\icuuc42.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\CoreFoundation%DebugSuffix%.dll" xcopy /y /d "%WebKit_Libraries%\bin32\CoreFoundation%DebugSuffix%.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\CoreFoundation.resources" xcopy /y /d /e /i "%WebKit_Libraries%\bin32\CoreFoundation.resources" "%CONFIGURATIONBUILDDIR%\bin32\CoreFoundation.resources"
if exist "%WebKit_Libraries%\bin32\objc%DebugSuffix%.dll" xcopy /y /d "%WebKit_Libraries%\bin32\objc%DebugSuffix%.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\ASL%DebugSuffix%.dll" xcopy /y /d "%WebKit_Libraries%\bin32\ASL%DebugSuffix%.dll" "%CONFIGURATIONBUILDDIR%\bin32"
if exist "%WebKit_Libraries%\bin32\libdispatch%DebugSuffix%.dll" xcopy /y /d "%WebKit_Libraries%\bin32\libdispatch%DebugSuffix%.dll" "%CONFIGURATIONBUILDDIR%\bin32"

cmd /c
