[tox]
envlist = lint, format, mypy, test

[testenv:test]
deps =
    pytest==9.1.1
commands =
    pytest tests {posargs}

[testenv:lint]
deps =
    flake8==7.3.0
commands =
    flake8 webkitsysprof tests

[testenv:format]
deps =
    black==26.5.1
commands =
    black --check --diff webkitsysprof tests

[testenv:mypy]
deps =
    mypy==2.3.0
commands =
    mypy webkitsysprof

[flake8]
max-line-length = 88
