/*
 * Copyright (C) 2006 Apple Computer, Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        InterfaceUUID=a9e9ef29-f20b-429d-848e-e5dadd32694a,
        ImplementationUUID=2d9b944e-88e3-451a-8640-06c593c339a8
    ] HTMLLinkElement : HTMLElement {
        attribute  boolean              disabled;
        attribute  [ConvertNullToNullString] DOMString            charset;
        attribute  [ConvertNullToNullString] DOMString            href;
        attribute  [ConvertNullToNullString] DOMString            hreflang;
        attribute  [ConvertNullToNullString] DOMString            media;
        attribute  [ConvertNullToNullString] DOMString            rel;
        attribute  [ConvertNullToNullString] DOMString            rev;
        attribute  [ConvertNullToNullString] DOMString            target;
        attribute  [ConvertNullToNullString] DOMString            type;

#if !defined(LANGUAGE_COM) || !LANGUAGE_COM
        // DOM Level 2 Style
        readonly attribute StyleSheet   sheet;
#endif

#if defined(LANGUAGE_OBJECTIVE_C) && LANGUAGE_OBJECTIVE_C
        // Objective-C extension:
        readonly attribute URL absoluteLinkURL;
#endif
    };

}
