/*
 * Copyright (C) 2006 Apple Computer, Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        InterfaceUUID=84050abc-45e6-4fd8-bdc3-29c7b4efb5cb,
        ImplementationUUID=e6de0d19-883e-4e87-9569-fd068e5ee17d
    ] HTMLPreElement : HTMLElement {
        // FIXME: DOM spec says that width should be of type DOMString
        // see http://bugs.webkit.org/show_bug.cgi?id=8992
        attribute long width;
        
        // Extensions
        attribute boolean wrap;
    };

}
