/*
 * Copyright (C) 2006, 2007, 2009 Apple Inc. All rights reserve
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        HasOverridingNameGetter
    ] HTMLFrameSetElement : HTMLElement {
        attribute [ConvertNullToNullString] DOMString cols;
        attribute [ConvertNullToNullString] DOMString rows;

#if !defined(LANGUAGE_OBJECTIVE_C) || !LANGUAGE_OBJECTIVE_C
        // Event handler attributes
        attribute [DontEnum] EventListener onbeforeunload;
        attribute [DontEnum] EventListener onhashchange;
        attribute [DontEnum] EventListener onmessage;
        attribute [DontEnum] EventListener onoffline;
        attribute [DontEnum] EventListener ononline;
        attribute [DontEnum] EventListener onpopstate;
        attribute [DontEnum] EventListener onresize;
        attribute [DontEnum] EventListener onstorage;
        attribute [DontEnum] EventListener onunload;

#if defined(ENABLE_ORIENTATION_EVENTS) && ENABLE_ORIENTATION_EVENTS
        attribute [DontEnum] EventListener onorientationchange;
#endif

        // Overrides of Element attributes (left in for completeness).
        // attribute [DontEnum] EventListener onblur;
        // attribute [DontEnum] EventListener onerror;
        // attribute [DontEnum] EventListener onfocus;
        // attribute [DontEnum] EventListener onload;

        // Not implemented yet.
        // attribute [DontEnum] EventListener onafterprint;
        // attribute [DontEnum] EventListener onbeforeprint;
        // attribute [DontEnum] EventListener onredo;
        // attribute [DontEnum] EventListener onundo;
#endif
    };

}
