/*
 * Copyright (C) 2006 Apple Computer, Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        HasIndexGetter,
        HasOverridingNameGetter,
        GenerateConstructor,
        InterfaceUUID=c7e79252-3b6d-4636-9efb-0667192ca5c3,
        ImplementationUUID=3561288f-5f67-4c45-9290-de4191d4c9c9
    ] HTMLFormElement : HTMLElement {
        readonly attribute HTMLCollection  elements;
        readonly attribute long            length;
                 attribute [ConvertNullToNullString] DOMString       name;
                 attribute [ConvertNullToNullString] DOMString       acceptCharset;
                 attribute [ConvertNullToNullString] DOMString       action;
                 attribute [ConvertNullToNullString] DOMString       encoding;  /* Netscape/Firefox legacy attribute. Same as enctype. */
                 attribute [ConvertNullToNullString] DOMString       enctype;
                 attribute [ConvertNullToNullString] DOMString       method;
                 attribute [ConvertNullToNullString] DOMString       target;
        
        void               submit();
        void               reset();
    };
}
