/*
 * Copyright (C) 2006, 2007 Apple Inc. All rights reserve
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        HasOverridingNameGetter,
        InterfaceUUID=5038a73d-c0db-4847-acb4-4c6d31f48790,
        ImplementationUUID=450f7bf6-fdc0-4a0f-b7e1-baea7f7e5732
    ] HTMLFrameSetElement : HTMLElement {

        attribute [ConvertNullToNullString] DOMString cols;
        attribute [ConvertNullToNullString] DOMString rows;

    };

}
