/*
 * Copyright (C) 2006, 2007 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        CustomPutFunction,
        CustomGetOwnPropertySlot,
        CustomCall,
        HasOverridingNameGetter,
        InterfaceUUID=9d04a3b8-9016-4b64-913a-3b00d548aca7,
        ImplementationUUID=2dd24554-6784-4ef9-9713-179f3d37b2f9
    ] HTMLObjectElement : HTMLElement {
        readonly attribute HTMLFormElement form;
                 attribute [ConvertNullToNullString] DOMString       code;
                 attribute [ConvertNullToNullString] DOMString       align;
                 attribute [ConvertNullToNullString] DOMString       archive;
                 attribute [ConvertNullToNullString] DOMString       border;
                 attribute [ConvertNullToNullString] DOMString       codeBase;
                 attribute [ConvertNullToNullString] DOMString       codeType;
                 attribute [ConvertNullToNullString] DOMString       data;
                 attribute boolean         declare;
                 attribute [ConvertNullToNullString] DOMString       height;
                 attribute long            hspace;
                 attribute [ConvertNullToNullString] DOMString       name;
                 attribute [ConvertNullToNullString] DOMString       standby;
                 attribute long            tabIndex;
                 attribute [ConvertNullToNullString] DOMString       type;
                 attribute [ConvertNullToNullString] DOMString       useMap;
                 attribute long            vspace;
                 attribute [ConvertNullToNullString] DOMString       width;

        // Introduced in DOM Level 2:
        readonly attribute [CheckFrameSecurity] Document        contentDocument;

#if !defined(LANGUAGE_COM)
#if ENABLE_SVG
        [SVGCheckSecurityDocument] SVGDocument getSVGDocument()
            raises(DOMException);
#endif
#endif

#if defined(LANGUAGE_OBJECTIVE_C)
        // Objective-C extension:
        readonly attribute URL             absoluteImageURL;
#endif
    };

}
