/*
 * Copyright (C) 2006, 2007 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        InterfaceUUID=0795de43-e0cb-429e-ae0b-d38dbb641fd7,
        ImplementationUUID=38c9e3c8-3384-40b6-a484-cb845c48b67d
    ] HTMLFrameElement : HTMLElement {

                 attribute [ConvertNullToNullString] DOMString       frameBorder;
                 attribute [ConvertNullToNullString] DOMString       longDesc;
                 attribute [ConvertNullToNullString] DOMString       marginHeight;
                 attribute [ConvertNullToNullString] DOMString       marginWidth;
                 attribute [ConvertNullToNullString] DOMString       name;
                 attribute boolean         noResize;
                 attribute [ConvertNullToNullString] DOMString       scrolling;
                 attribute [ConvertNullToNullString, CustomSetter] DOMString       src;

        // Introduced in DOM Level 2:
        readonly attribute [CheckFrameSecurity] Document        contentDocument;

#if !defined(LANGUAGE_COM)
        // Extensions
        readonly attribute DOMWindow contentWindow;

#if ENABLE_SVG
        [SVGCheckSecurityDocument] SVGDocument getSVGDocument()
            raises(DOMException);
#endif
#endif

                 attribute [ConvertNullToNullString, CustomSetter] DOMString       location;
        readonly attribute long            width;
        readonly attribute long            height;

    };

}
