/*
 * Copyright (C) 2006 Apple Computer, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        InterfaceUUID=434b1be5-408e-45b5-be83-c70e11e9bb37,
        ImplementationUUID=1dc8508e-53c4-4e7e-93c0-16772372b2dc
    ] HTMLBaseFontElement : HTMLElement {
        attribute [ConvertNullToNullString] DOMString color;
        attribute [ConvertNullToNullString] DOMString face;
#if defined(LANGUAGE_OBJECTIVE_C)
        attribute [ConvertToString] DOMString size; // this changed to a long, but our existing API is a string
#else
        attribute long size;
#endif
    };
}
