/*
 * Copyright (C) 2006, 2007 Apple Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        InterfaceUUID=3ad21d30-ce64-4a6f-9296-c07a16170783,
        ImplementationUUID=36fe6075-c9c1-4f22-bbc2-dd440f21f7cf
    ] HTMLTableCellElement : HTMLElement {

        readonly attribute long            cellIndex;
                 attribute [ConvertNullToNullString] DOMString       abbr;
                 attribute [ConvertNullToNullString] DOMString       align;
                 attribute [ConvertNullToNullString] DOMString       axis;
                 attribute [ConvertNullToNullString] DOMString       bgColor;
                 attribute [ConvertNullToNullString] DOMString       ch;
                 attribute [ConvertNullToNullString] DOMString       chOff;
                 attribute long            colSpan;
                 attribute [ConvertNullToNullString] DOMString       headers;
                 attribute [ConvertNullToNullString] DOMString       height;
                 attribute boolean         noWrap;
                 attribute long            rowSpan;
                 attribute [ConvertNullToNullString] DOMString       scope;
                 attribute [ConvertNullToNullString] DOMString       vAlign;
                 attribute [ConvertNullToNullString] DOMString       width;

    };

}
