/*
 * Copyright (C) 2006, 2007 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface [
        GenerateConstructor,
        GenerateNativeConverter,
        CustomPushEventHandlerScope,
        InterfaceUUID=b2f172f1-d209-446f-8143-5f21de678f95,
        ImplementationUUID=c81b0e16-a2b9-448b-ad0a-81c9346d6f8a
    ] HTMLElement : Element {
                 // iht.com relies on id returning the empty string when no id is present. 
                 // Other browsers do this as well. So we don't convert null to JS null.
                 attribute [ConvertNullToNullString] DOMString id;
                 attribute [ConvertNullToNullString] DOMString title;
                 attribute [ConvertNullToNullString] DOMString lang;
                 attribute [ConvertNullToNullString] DOMString dir;
                 attribute [ConvertNullToNullString] DOMString className;

                 attribute long            tabIndex;

        // Extensions
                 attribute [ConvertNullToNullString] DOMString innerHTML
                     setter raises(DOMException);
                 attribute [ConvertNullToNullString] DOMString innerText
                     setter raises(DOMException);
                 attribute [ConvertNullToNullString] DOMString outerHTML
                     setter raises(DOMException);
                 attribute [ConvertNullToNullString] DOMString outerText
                     setter raises(DOMException);

        Element insertAdjacentElement(in DOMString where,
                                      in Element element)
            raises(DOMException);
        void insertAdjacentHTML(in DOMString where,
                                in DOMString html)
            raises(DOMException);
        void insertAdjacentText(in DOMString where,
                                in DOMString text)
            raises(DOMException);

        readonly attribute HTMLCollection children;

                 attribute [ConvertNullToNullString] DOMString contentEditable;
        readonly attribute boolean isContentEditable;

#if defined(LANGUAGE_OBJECTIVE_C) && LANGUAGE_OBJECTIVE_C
        readonly attribute DOMString titleDisplayString;
#endif
    };

}
