/*
 * Copyright (C) 2006 Apple Computer, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

module html {
    interface [LegacyParent=KJS::JSHTMLElement] HTMLImageElement : HTMLElement {
        attribute DOMString name;
        attribute DOMString align;
        attribute DOMString alt;
        // FIXME: According to the DOM spec border should be of type DOMString
        // see http://bugzilla.opendarwin.org/show_bug.cgi?id=8992
        attribute long border;        
        attribute long height;
        attribute long hspace;
        attribute boolean isMap;
        attribute DOMString longDesc;
        attribute DOMString src;
        attribute DOMString useMap;
        attribute long vspace;
        attribute long width;
        
        // Extensions
        readonly attribute boolean complete;
        readonly attribute long x;
        readonly attribute long y;
    };
}
