/*
 * Copyright (C) 2026 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "WebCorePrefix.h"

#ifdef __cplusplus
#undef new
#undef delete

#include <JavaScriptCore/HeapAnalyzer.h>
#include <JavaScriptCore/JSCJSValueInlines.h>
#include <JavaScriptCore/JSGlobalObject.h>
#include <JavaScriptCore/JSObject.h>
#include <JavaScriptCore/JSStringInlines.h>
#include <JavaScriptCore/Lookup.h>
#include <JavaScriptCore/SubspaceInlines.h>

#include <pal/SessionID.h>
#include <wtf/PointerPreparations.h>
#include <wtf/Range.h>
#include <wtf/persistence/PersistentCoders.h>
#include <wtf/persistence/PersistentDecoder.h>
#include <wtf/persistence/PersistentEncoder.h>
#if PLATFORM(COCOA)
#include <wtf/spi/cocoa/SecuritySPI.h>
#endif

#include "ActiveDOMObject.h"
#include "BlobData.h"
#include "BlobDataFileReference.h"
#include "CacheValidation.h"
#include "CertificateInfo.h"
#include "ContentSecurityPolicyResponseHeaders.h"
#include "ContextDestructionObserverInlines.h"
#include "DOMHighResTimeStamp.h"
#include "Document.h"
#include "EventTargetInlines.h"
#include "ExtendedDOMClientIsoSubspaces.h"
#include "ExtendedDOMIsoSubspaces.h"
#include "FetchOptions.h"
#include "FetchOptionsCache.h"
#include "FetchOptionsCredentials.h"
#include "FetchOptionsDestination.h"
#include "FetchOptionsMode.h"
#include "FetchOptionsRedirect.h"
#include "FormData.h"
#include "FrameLoaderTypes.h"
#include "HTTPHeaderMap.h"
#include "HTTPHeaderNames.h"
#include "ImageBitmap.h"
#include "JSDOMAttribute.h"
#include "JSDOMBinding.h"
#include "JSDOMConstructorBase.h"
#include "JSDOMConvertBase.h"
#include "JSDOMConvertDictionary.h"
#include "JSDOMConvertInterface.h"
#include "JSDOMConvertNumbers.h"
#include "JSDOMConvertStrings.h"
#include "JSDOMExceptionHandling.h"
#include "JSDOMGlobalObjectInlines.h"
#include "JSDOMOperation.h"
#include "JSDOMWrapperCache.h"
#include "JSValueInWrappedObject.h"
#include "NetworkLoadMetrics.h"
#include "Node.h"
#include "ParsedContentRange.h"
#include "PolicyContainer.h"
#include "ResourceLoadPriority.h"
#include "ResourceRequest.h"
#include "ResourceResponse.h"
#include "SecurityOrigin.h"
#include "TrustedFonts.h"
#include "WebCoreJSClientData.h"
#include "WebCoreOpaqueRoot.h"
#include "WebKitFontFamilyNames.h"
#include "WindowOrWorkerGlobalScope.h"

#include "CSSPrimitiveNumericUnits.h"
#include "HTMLElement.h"
#include "HTMLElementTypeHelpers.h"
#include "HTMLNames.h"
#include "RenderBox.h"

#if PLATFORM(MAC)
#include <ATS/SFNTLayoutTypes.h>
#include <ATS/SFNTTypes.h>
#include <CoreFoundation/CoreFoundation.h>
#include <CoreText/CoreText.h>
#include <IOSurface/IOSurface.h>
#include <ImageIO/ImageIO.h>
#endif

#include <JavaScriptCore/ArrayPrototype.h>
#include <JavaScriptCore/Breakpoint.h>
#include <JavaScriptCore/BuiltinNames.h>
#include <JavaScriptCore/ButterflyInlinesLight.h>
#include <JavaScriptCore/BytecodeIntrinsicRegistry.h>
#include <JavaScriptCore/ConsoleMessage.h>
#include <JavaScriptCore/ConsoleTypes.h>
#include <JavaScriptCore/DataView.h>
#include <JavaScriptCore/Debugger.h>
#include <JavaScriptCore/DebuggerParseData.h>
#include <JavaScriptCore/DebuggerPrimitives.h>
#include <JavaScriptCore/Float16Array.h>
#include <JavaScriptCore/FunctionPrototype.h>
#include <JavaScriptCore/GenericTypedArrayView.h>
#include <JavaScriptCore/JSArray.h>
#include <JavaScriptCore/JSArrayBufferViewInlines.h>
#include <JavaScriptCore/JSArrayBufferViewInlinesLight.h>
#include <JavaScriptCore/JSCBuiltins.h>
#include <JavaScriptCore/JSDataView.h>
#include <JavaScriptCore/JSGenericTypedArrayView.h>
#include <JavaScriptCore/JSGenericTypedArrayViewInlinesLight.h>
#include <JavaScriptCore/JSONObject.h>
#include <JavaScriptCore/JSPromise.h>
#include <JavaScriptCore/JSTypedArrays.h>
#include <JavaScriptCore/ObjectConstructor.h>
#include <JavaScriptCore/TopExceptionScope.h>
#include <JavaScriptCore/TypedArrayAdaptors.h>
#include <JavaScriptCore/TypedArrays.h>
#include <JavaScriptCore/Uint32Array.h>
#include <JavaScriptCore/Uint8Array.h>
#include <JavaScriptCore/Uint8ClampedArray.h>
#include <wtf/AbstractThreadSafeRefCountedAndCanMakeWeakPtr.h>
#include <wtf/AggregateLogger.h>
#include <wtf/Identified.h>
#include <wtf/IsIncreasing.h>
#include <wtf/LoggerHelper.h>
#include <wtf/MachSendRight.h>
#include <wtf/MemoryPressureHandler.h>
#include <wtf/MessageQueue.h>
#include <wtf/NativePromise.h>
#include <wtf/ReducedResolutionSeconds.h>
#include <wtf/SortedArrayMap.h>

#include "AXObjectTypes.h"
#include "AbortSignal.h"
#include "ActiveDOMCallback.h"
#include "AudioArray.h"
#include "AudioBus.h"
#include "AudioChannel.h"
#if ENABLE(WEB_AUDIO)
#include "AudioNode.h"
#endif
#include "AudioTrack.h"
#include "AudioTrackClient.h"
#include "AudioTrackPrivateClient.h"
#include "AuthenticationClient.h"
#include "AutoplayEvent.h"
#include "Blob.h"
#include "BlobPropertyBag.h"
#include "BlobResourceHandle.h"
#include "BlobResourceHandleBase.h"
#include "ByteArrayPixelBuffer.h"
#include "CDMClient.h"
#include "CDMTypesForward.h"
#include "CSSCustomPropertyValue.h"
#include "CSSRuleList.h"
#include "CSSStyleSheet.h"
#include "CSSSubstitutionValue.h"
#include "CSSToLengthConversionData.h"
#include "CSSWideKeyword.h"
#include "CacheStorageConnection.h"
#include "CallbackResult.h"
#include "CanvasBase.h"
#include "CanvasNoiseInjection.h"
#include "CaptionUserPreferences.h"
#include "ChannelCountMode.h"
#include "ChannelInterpretation.h"
#include "ClientOrigin.h"
#include "Cookie.h"
#include "CopyImageOptions.h"
#include "CustomElementFormValue.h"
#include "CustomElementReactionQueue.h"
#include "DOMCacheEngine.h"
#include "DOMCacheIdentifier.h"
#include "DOMFormData.h"
#include "DOMMatrix2DInit.h"
#include "DOMPromiseProxy.h"
#include "DOMRectInit.h"
#include "DOMRectReadOnly.h"
#include "DOMWindow.h"
#include "DocumentQuirks.h"
#include "DocumentSettingsValues.h"
#include "EndingType.h"
#include "EventNames.h"
#include "EventTimingInteractionID.h"
#include "FetchHeaders.h"
#include "FetchHeadersGuard.h"
#include "File.h"
#include "FileReaderLoader.h"
#include "FileStreamClient.h"
#include "Float16ArrayPixelBuffer.h"
#include "FormAssociatedElement.h"
#include "FormState.h"
#include "FormSubmission.h"
#include "GenericMediaQueryTypes.h"
#include "GlobalWindowIdentifier.h"
#include "GraphicsContextGLAttributes.h"
#include "GraphicsLayerContentsDisplayDelegate.h"
#include "GraphicsTypesGL.h"
#include "HTMLCanvasElement.h"
#include "HTMLFormElement.h"
#include "HTMLFrameOwnerElement.h"
#include "HTMLMediaElement.h"
#include "HTMLMediaElementEnums.h"
#include "HTMLMediaElementIdentifier.h"
#include "HTTPParsers.h"
#include "IDBBindingUtilities.h"
#include "IDBIndexIdentifier.h"
#include "IDBKey.h"
#include "IDBKeyData.h"
#include "IDBKeyPath.h"
#if USE(CG)
#include "IOSurfacePool.h"
#include "IOSurfacePoolIdentifier.h"
#endif
#include "ImageBuffer.h"
#include "ImageBufferAllocator.h"
#include "ImageBufferBackend.h"
#include "ImageBufferBackendParameters.h"
#include "ImageData.h"
#include "ImageDataArray.h"
#include "ImageDataPixelFormat.h"
#include "ImageDataSettings.h"
#include "IndexKey.h"
#include "IndexedDB.h"
#if ENABLE(WEB_AUDIO)
#include "JSAudioNode.h"
#endif
#include "JSBlob.h"
#include "JSCallbackData.h"
#include "JSDOMBindingSecurity.h"
#include "JSDOMConstructor.h"
#include "JSDOMConstructorNotConstructable.h"
#include "JSDOMConvert.h"
#include "JSDOMConvertAny.h"
#include "JSDOMConvertBoolean.h"
#include "JSDOMConvertBufferSource.h"
#include "JSDOMConvertCallbacks.h"
#include "JSDOMConvertDate.h"
#include "JSDOMConvertEnumeration.h"
#include "JSDOMConvertEventListener.h"
#include "JSDOMConvertIndexedDB.h"
#include "JSDOMConvertJSON.h"
#include "JSDOMConvertNull.h"
#include "JSDOMConvertNullable.h"
#include "JSDOMConvertObject.h"
#include "JSDOMConvertOptional.h"
#include "JSDOMConvertPromise.h"
#include "JSDOMConvertRecord.h"
#include "JSDOMConvertSequences.h"
#include "JSDOMConvertSerializedScriptValue.h"
#include "JSDOMConvertUndefined.h"
#include "JSDOMConvertUnion.h"
#include "JSDOMGuardedObject.h"
#include "JSDOMOperationReturningPromise.h"
#include "JSDOMPromise.h"
#include "JSDOMPromiseDeferred.h"
#include "JSDOMWindowBase.h"
#include "JSElement.h"
#include "JSElementCustom.h"
#include "JSEvent.h"
#include "JSEventCustom.h"
#include "JSEventListener.h"
#include "JSEventTarget.h"
#include "JSEventTargetCustom.h"
#include "JSHTMLElement.h"
#include "JSHTMLMediaElement.h"
#include "JSImageData.h"
#include "JSNode.h"
#include "JSNodeCustom.h"
#include "JSNodeCustomInlines.h"
#include "JSOffscreenCanvas.h"
#include "LayerHostingContextIdentifier.h"
#include "LocalDOMWindow.h"
#include "LocalDOMWindowProperty.h"
#include "MediaCanStartListener.h"
#include "MediaControllerInterface.h"
#include "MediaElementSession.h"
#include "MediaList.h"
#include "MediaPlaybackTarget.h"
#include "MediaPlaybackTargetClient.h"
#include "MediaPlayer.h"
#include "MediaPlayerClientIdentifier.h"
#include "MediaPlayerIdentifier.h"
#include "MediaProducer.h"
#include "MediaPromiseTypes.h"
#include "MediaQuery.h"
#include "MediaQueryParserContext.h"
#include "MediaSessionIdentifier.h"
#include "MediaSessionManagerInterface.h"
#include "MediaUniqueIdentifier.h"
#include "MediaUsageInfo.h"
#include "MessageTargetForTesting.h"
#include "NowPlayingInfo.h"
#include "NowPlayingMetadataObserver.h"
#include "OffscreenCanvas.h"
#include "PerformanceEventTimingCandidate.h"
#include "PixelBuffer.h"
#include "PixelBufferFormat.h"
#include "PlaneLayout.h"
#include "PlatformMediaDecodingType.h"
#include "PlatformMediaError.h"
#include "PlatformMediaSession.h"
#include "PlatformMediaSessionInterface.h"
#include "PlatformMediaSessionTypes.h"
#include "PlatformTextTrack.h"
#include "PlatformTimeRanges.h"
#include "PlatformVideoColorPrimaries.h"
#include "PlatformVideoColorSpace.h"
#include "PlatformVideoMatrixCoefficients.h"
#include "PlatformVideoTransferCharacteristics.h"
#include "PredefinedColorSpace.h"
#include "ProcessIdentity.h"
#include "PushSubscriptionIdentifier.h"
#include "PushSubscriptionOwner.h"
#include "Quirks.h"
#include "QuirksData.h"
#include "RadioButtonGroups.h"
#include "RemoteFrame.h"
#include "ResourceHandle.h"
#include "RetrieveRecordsOptions.h"
#include "SVGAngle.h"
#include "SVGAngleValue.h"
#include "SVGAnimatedDecoratedProperty.h"
#include "SVGAnimatedPrimitiveProperty.h"
#include "SVGAnimatedProperty.h"
#include "SVGAnimatedPropertyAccessor.h"
#include "SVGAnimatedPropertyAccessorImpl.h"
#include "SVGAnimatedPropertyAnimator.h"
#include "SVGAnimatedPropertyAnimatorImpl.h"
#include "SVGAnimatedPropertyBase.h"
#include "SVGAnimatedPropertyImpl.h"
#include "SVGAnimatedPropertyList.h"
#include "SVGAnimatedPropertyPairAccessor.h"
#include "SVGAnimatedPropertyPairAccessorImpl.h"
#include "SVGAnimatedPropertyPairAnimator.h"
#include "SVGAnimatedPropertyPairAnimatorImpl.h"
#include "SVGAnimatedString.h"
#include "SVGAnimatedValueProperty.h"
#include "SVGAnimationAdditiveFunction.h"
#include "SVGAnimationAdditiveListFunction.h"
#include "SVGAnimationAdditiveListFunctionImpl.h"
#include "SVGAnimationAdditiveValueFunction.h"
#include "SVGAnimationAdditiveValueFunctionImpl.h"
#include "SVGAnimationDiscreteFunction.h"
#include "SVGAnimationDiscreteFunctionImpl.h"
#include "SVGAnimationFunction.h"
#include "SVGAttributeAnimator.h"
#include "SVGDecoratedEnumeration.h"
#include "SVGDecoratedPrimitive.h"
#include "SVGDecoratedProperty.h"
#include "SVGElement.h"
#include "SVGLength.h"
#include "SVGLengthContext.h"
#include "SVGLengthList.h"
#include "SVGLengthValue.h"
#include "SVGList.h"
#include "SVGMarkerTypes.h"
#include "SVGMatrix.h"
#include "SVGMemberAccessor.h"
#include "SVGNames.h"
#include "SVGNumber.h"
#include "SVGNumberList.h"
#include "SVGParsingError.h"
#include "SVGPathSeg.h"
#include "SVGPathSegList.h"
#include "SVGPoint.h"
#include "SVGPointList.h"
#include "SVGPointerMemberAccessor.h"
#include "SVGPreserveAspectRatio.h"
#include "SVGPreserveAspectRatioValue.h"
#include "SVGPrimitiveList.h"
#include "SVGProperty.h"
#include "SVGPropertyAccessor.h"
#include "SVGPropertyAccessorImpl.h"
#include "SVGPropertyList.h"
#include "SVGPropertyOwner.h"
#include "SVGPropertyOwnerRegistry.h"
#include "SVGPropertyRegistry.h"
#include "SVGRect.h"
#include "SVGSharedPrimitiveProperty.h"
#include "SVGStringList.h"
#include "SVGTests.h"
#include "SVGTransform.h"
#include "SVGTransformDistance.h"
#include "SVGTransformList.h"
#include "SVGTransformValue.h"
#include "SVGUnitTypes.h"
#include "SVGValueProperty.h"
#include "SVGValuePropertyList.h"
#include "StyleSheet.h"
#include "TextTrack.h"
#include "TextTrackClient.h"
#include "TextTrackCue.h"
#include "ThreadGlobalData.h"
#include "ThreadSafeDataBuffer.h"
#include "ThreadableLoaderClient.h"
#include "TrackBase.h"
#include "TrackPrivateBaseClient.h"
#include "URLRegistry.h"
#include "UserAgent.h"
#include "VideoColorSpaceInit.h"
#include "VideoFrame.h"
#include "VideoPixelFormat.h"
#include "VideoPlaybackQualityMetrics.h"
#include "VideoTarget.h"
#include "VideoTrackClient.h"
#include "VisibilityChangeClient.h"
#include "WebCodecsAlphaOption.h"
#include "WebCoreOpaqueRootInlines.h"
#include "WebGLContextAttributes.h"
#include "WorkerGlobalScope.h"
#include "WorkerOrWorkletGlobalScope.h"
#include "WorkerOrWorkletScriptController.h"
#include "WorkerType.h"


#define new ("if you use new/delete make sure to include config.h at the top of the file"())
#define delete ("if you use new/delete make sure to include config.h at the top of the file"())
#endif
