;; Tools/Scripts/run-jsc -e "'load(\"JSTests/wasm/gc/wast.js\"); writeFile(\"JSTests/wasm/stress/type-index-abstract-heap-types-nulls-and-casts.wasm\", WebAssemblyText.encode(read(\"JSTests/wasm/stress/type-index-abstract-heap-types-nulls-and-casts.wat\")))'"
(module
  (type $S (struct (field i32)))
  (type $A (array i32))
  (func (export "nullFuncref") (result funcref) (ref.null func))
  (func (export "nullExternref") (result externref) (ref.null extern))
  (func (export "nullAnyref") (result anyref) (ref.null any))
  (func (export "nullEqref") (result eqref) (ref.null eq))
  (func (export "nullI31ref") (result i31ref) (ref.null i31))
  (func (export "nullStructref") (result structref) (ref.null struct))
  (func (export "nullArrayref") (result arrayref) (ref.null array))
  (func (export "nullNone") (result nullref) (ref.null none))
  (func (export "nullNofunc") (result nullfuncref) (ref.null nofunc))
  (func (export "nullNoextern") (result nullexternref) (ref.null noextern))

  (func (export "castI31ToAny") (param i32) (result anyref)
    (ref.cast anyref (ref.i31 (local.get 0))))
  (func (export "testI31IsEq") (param i32) (result i32)
    (ref.test eqref (ref.i31 (local.get 0))))
  (func (export "testStructIsAny") (result i32)
    (ref.test anyref (struct.new $S (i32.const 1))))
  (func (export "testArrayIsStruct") (result i32)
    (ref.test structref (array.new_default $A (i32.const 1))))
  (func (export "castStructToStructref") (result structref)
    (ref.cast structref (struct.new $S (i32.const 7))))
  (func (export "castArrayToArrayref") (result arrayref)
    (ref.cast arrayref (array.new_default $A (i32.const 2))))
  (func (export "castFailAnyToStruct") (param anyref) (result (ref null $S))
    (ref.cast (ref null $S) (local.get 0)))
)
