#!/usr/bin/env python3

import sys

sys.stdout.write(
    'Content-Security-Policy: sandbox allow-scripts\r\n'
    'Content-Type: text/html\r\n\r\n'
    '<!DOCTYPE html>\n'
    '<title>Requesting notification permission from a sandboxed top level document must not crash the UI process</title>\n'
    '<pre id="log"></pre>\n'
    '<script>\n'
    'testRunner?.dumpAsText();\n'
    'testRunner?.waitUntilDone();\n'
    'const out = s => document.getElementById("log").textContent += s + "\\n";\n'
    '\n'
    '// A document sandboxed by a CSP header has an opaque origin, and\n'
    '// SecurityOriginData::toString() returns a null string for every opaque origin. That null\n'
    '// string is what the web process sends in RequestNotificationPermission, and in the UI process\n'
    '// it turns back into a null SecurityOriginData, which is the empty value of\n'
    '// WebPageProxy::notificationPermissionRequesters.\n'
    '//\n'
    '// The document is still a secure context (a sandboxed document is judged by its URL, not by its\n'
    '// opaque origin) and it is trivially same origin as the top document, because it is the top\n'
    '// document, so neither of the gates in Notification::requestPermission() stops it.\n'
    '//\n'
    '// "granted" rather than "denied" is what proves the request reached the UI process, so this\n'
    '// test would go vacuous rather than silently keep passing if those gates ever changed.\n'
    'if (!window.internals) {\n'
    '    out("FAIL: this test needs window.internals for the user gesture");\n'
    '    testRunner?.notifyDone();\n'
    '} else {\n'
    '    internals.withUserGesture(() => {\n'
    '        Notification.requestPermission().then(permission => {\n'
    '            out(permission == "granted"\n'
    '                ? "PASS: a sandboxed top level document was prompted for notification permission without crashing the UI process"\n'
    '                : "FAIL: notification permission was " + permission + ", so the request never reached the UI process");\n'
    '            testRunner?.notifyDone();\n'
    '        }, error => {\n'
    '            out("FAIL: " + error);\n'
    '            testRunner?.notifyDone();\n'
    '        });\n'
    '    });\n'
    '}\n'
    '</script>\n'
)
