/*
 * Copyright (C) 2025 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once

#include <wtf/TZoneMalloc.h>

#ifndef DOM_TZONE

#define DOM_MAKE_TZONE_ALLOCATED WTF_MAKE_TZONE_ALLOCATED
#define DOM_MAKE_TZONE_ALLOCATED_EXPORT WTF_MAKE_TZONE_ALLOCATED_EXPORT
#define DOM_MAKE_STRUCT_TZONE_ALLOCATED WTF_MAKE_STRUCT_TZONE_ALLOCATED
#define DOM_MAKE_TZONE_ALLOCATED_TEMPLATE WTF_MAKE_TZONE_ALLOCATED_TEMPLATE
#define DOM_MAKE_TZONE_ALLOCATED_TEMPLATE_EXPORT WTF_MAKE_TZONE_ALLOCATED_TEMPLATE_EXPORT
#define DOM_MAKE_COMPACT_TZONE_ALLOCATED WTF_MAKE_COMPACT_TZONE_ALLOCATED
#define DOM_MAKE_COMPACT_TZONE_ALLOCATED_EXPORT WTF_MAKE_COMPACT_TZONE_ALLOCATED_EXPORT
#define DOM_MAKE_TZONE_OR_ISO_ALLOCATED WTF_MAKE_TZONE_OR_ISO_ALLOCATED
#define DOM_MAKE_TZONE_OR_ISO_ALLOCATED_EXPORT WTF_MAKE_TZONE_OR_ISO_ALLOCATED_EXPORT
#define DOM_MAKE_TZONE_OR_ISO_ALLOCATED_TEMPLATE WTF_MAKE_TZONE_OR_ISO_ALLOCATED_TEMPLATE
#define DOM_MAKE_COMPACT_TZONE_OR_ISO_ALLOCATED WTF_MAKE_COMPACT_TZONE_OR_ISO_ALLOCATED
#define DOM_MAKE_COMPACT_TZONE_OR_ISO_ALLOCATED_EXPORT WTF_MAKE_COMPACT_TZONE_OR_ISO_ALLOCATED_EXPORT
#define DOM_MAKE_TZONE_ALLOCATED_TEMPLATE_IMPL WTF_MAKE_TZONE_ALLOCATED_TEMPLATE_IMPL
#define DOM_MAKE_TZONE_OR_ISO_ALLOCATED_TEMPLATE_IMPL WTF_MAKE_TZONE_OR_ISO_ALLOCATED_TEMPLATE_IMPL
#define DOM_MAKE_TZONE_ALLOCATED_TEMPLATE_IMPL_WITH_MULTIPLE_OR_SPECIALIZED_PARAMETERS WTF_MAKE_TZONE_ALLOCATED_TEMPLATE_IMPL_WITH_MULTIPLE_OR_SPECIALIZED_PARAMETERS
#define DOM_MAKE_TZONE_NON_HEAP_ALLOCATABLE WTF_MAKE_TZONE_NON_HEAP_ALLOCATABLE
#define DOM_MAKE_TZONE_OR_ISO_NON_HEAP_ALLOCATABLE WTF_MAKE_TZONE_OR_ISO_NON_HEAP_ALLOCATABLE

#endif // DOM_TZONE
