/*
 * Copyright (C) 2006, 2007, 2011, 2015 Apple Inc. All rights reserved.
 * Copyright (C) 2006, 2007 Samuel Weinig <sam@webkit.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

[
    Conditional=TOUCH_EVENTS,
    ImplementedBy=DocumentTouch
] partial interface Document {
    // FIXME: This has been dropped from the standard now that Touch has a constructor.
    [NewObject] Touch createTouch(optional WindowProxy? window = null, optional EventTarget? target = null,
        optional long identifier = 0,
        optional long pageX = 0, optional long pageY = 0, optional long screenX = 0, optional long screenY = 0,
        optional long webkitRadiusX = 0, optional long webkitRadiusY = 0,
        optional unrestricted float webkitRotationAngle = NaN, optional unrestricted float webkitForce = NaN);
    [NewObject] TouchList createTouchList(Touch... touches);
};
