/*
 * Copyright (C) 2022 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

[
    GenerateIsReachable=ImplElementRoot,
    GenerateAddOpaqueRoot=element,
    Exposed=Window,
    EnabledBySetting=FormAssociatedCustomElementsEnabled,
] interface ElementInternals {
    readonly attribute ShadowRoot? shadowRoot;

    [Custom] undefined setFormValue(any value, optional any state);

    readonly attribute HTMLFormElement? form;

    undefined setValidity(optional ValidityStateFlags flags = {}, optional DOMString message, optional HTMLElement validationAnchor);
    readonly attribute boolean willValidate;
    readonly attribute ValidityState validity;
    readonly attribute DOMString validationMessage;
    boolean checkValidity();
    boolean reportValidity();

    readonly attribute NodeList labels;

    [EnabledBySetting=CustomStateSetEnabled, SameObject] readonly attribute CustomStateSet states;

    [Reflect, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? role;
    [Reflect=aria_activedescendant, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute Element? ariaActiveDescendantElement;
    [Reflect=aria_atomic, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaAtomic;
    [Reflect=aria_autocomplete, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaAutoComplete;
    [Reflect=aria_busy, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaBusy;
    [Reflect=aria_checked, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaChecked;
    [Reflect=aria_colcount, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaColCount;
    [Reflect=aria_colindex, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaColIndex;
    [Reflect=aria_colspan, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaColSpan;
    [CustomGetter, Reflect=aria_controls, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaControlsElements;
    [Reflect=aria_current, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaCurrent;
    [CustomGetter, Reflect=aria_describedby, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaDescribedByElements;
    [CustomGetter, Reflect=aria_details, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaDetailsElements;
    [Reflect=aria_disabled, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaDisabled;
    [CustomGetter, Reflect=aria_errormessage, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaErrorMessageElements;
    [Reflect=aria_expanded, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaExpanded;
    [CustomGetter, Reflect=aria_flowto, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaFlowToElements;
    [Reflect=aria_haspopup, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaHasPopup;
    [Reflect=aria_hidden, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaHidden;
    [Reflect=aria_invalid, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaInvalid;
    [Reflect=aria_keyshortcuts, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaKeyShortcuts;
    [Reflect=aria_label, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaLabel;
    [CustomGetter, Reflect=aria_labelledby, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaLabelledByElements;
    [Reflect=aria_level, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaLevel;
    [Reflect=aria_live, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaLive;
    [Reflect=aria_modal, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaModal;
    [Reflect=aria_multiline, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaMultiLine;
    [Reflect=aria_multiselectable, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaMultiSelectable;
    [Reflect=aria_orientation, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaOrientation;
    [CustomGetter, Reflect=aria_owns, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute FrozenArray<Element>? ariaOwnsElements;
    [Reflect=aria_placeholder, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaPlaceholder;
    [Reflect=aria_posinset, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaPosInSet;
    [Reflect=aria_pressed, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaPressed;
    [Reflect=aria_readonly, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaReadOnly;
    [Reflect=aria_relevant, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaRelevant;
    [Reflect=aria_required, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaRequired;
    [Reflect=aria_roledescription, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaRoleDescription;
    [Reflect=aria_rowcount, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaRowCount;
    [Reflect=aria_rowindex, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaRowIndex;
    [Reflect=aria_rowspan, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaRowSpan;
    [Reflect=aria_selected, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaSelected;
    [Reflect=aria_setsize, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaSetSize;
    [Reflect=aria_sort, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaSort;
    [Reflect=aria_valuemax, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaValueMax;
    [Reflect=aria_valuemin, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaValueMin;
    [Reflect=aria_valuenow, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaValueNow;
    [Reflect=aria_valuetext, EnabledBySetting=DefaultARIAForCustomElementsEnabled] attribute DOMString? ariaValueText;
};
