/*
 * Copyright (C) 2006, 2007 Apple Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module events {

    // Introduced in DOM Level 2:
    interface MouseEvent : UIEvent {
        readonly attribute long             screenX;
        readonly attribute long             screenY;
        readonly attribute long             clientX;
        readonly attribute long             clientY;
        readonly attribute [Conditional=POINTER_LOCK, V8EnabledAtRuntime] long webkitMovementX;
        readonly attribute [Conditional=POINTER_LOCK, V8EnabledAtRuntime] long webkitMovementY;
        readonly attribute boolean          ctrlKey;
        readonly attribute boolean          shiftKey;
        readonly attribute boolean          altKey;
        readonly attribute boolean          metaKey;
        readonly attribute unsigned short   button;
        readonly attribute EventTarget      relatedTarget;
        
        [ObjCLegacyUnnamedParameters] void initMouseEvent(in [Optional=DefaultIsUndefined] DOMString type, 
                                           in [Optional=DefaultIsUndefined] boolean canBubble, 
                                           in [Optional=DefaultIsUndefined] boolean cancelable, 
                                           in [Optional=DefaultIsUndefined] DOMWindow view, 
                                           in [Optional=DefaultIsUndefined] long detail, 
                                           in [Optional=DefaultIsUndefined] long screenX, 
                                           in [Optional=DefaultIsUndefined] long screenY, 
                                           in [Optional=DefaultIsUndefined] long clientX, 
                                           in [Optional=DefaultIsUndefined] long clientY, 
                                           in [Optional=DefaultIsUndefined] boolean ctrlKey, 
                                           in [Optional=DefaultIsUndefined] boolean altKey, 
                                           in [Optional=DefaultIsUndefined] boolean shiftKey, 
                                           in [Optional=DefaultIsUndefined] boolean metaKey, 
                                           in [Optional=DefaultIsUndefined] unsigned short button, 
                                           in [Optional=DefaultIsUndefined] EventTarget relatedTarget);

        // extensions
        readonly attribute long             offsetX;
        readonly attribute long             offsetY;
        readonly attribute long             x;
        readonly attribute long             y;
        readonly attribute Node             fromElement;
        readonly attribute Node             toElement;

#if defined(LANGUAGE_JAVASCRIPT) && LANGUAGE_JAVASCRIPT
        readonly attribute Clipboard        dataTransfer;
#endif
    };

}
