/*
 * Copyright (C) 2006 Apple Inc.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

// Introduced in DOM Level 2:
[
    Constructor,
    ConstructorCallWith=Document,
    ImplementationLacksVTable,
    ExportMacro=WEBCORE_EXPORT,
] interface Range {

    readonly attribute Node startContainer;
    readonly attribute long startOffset;
    readonly attribute Node endContainer;
    readonly attribute long endOffset;
    readonly attribute boolean collapsed;
    readonly attribute Node commonAncestorContainer;

    [ObjCLegacyUnnamedParameters, RaisesException] void setStart(Node refNode,
                                 [Default=Undefined] optional long offset);
    [ObjCLegacyUnnamedParameters, RaisesException] void setEnd(Node refNode,
                               [Default=Undefined] optional long offset);
    [RaisesException] void setStartBefore(Node refNode);
    [RaisesException] void setStartAfter(Node refNode);
    [RaisesException] void setEndBefore(Node refNode);
    [RaisesException] void setEndAfter(Node refNode);
    void collapse([Default=Undefined] optional boolean toStart);
    [RaisesException] void selectNode(Node refNode);
    [RaisesException] void selectNodeContents(Node refNode);

    // CompareHow
    const unsigned short START_TO_START = 0;
    const unsigned short START_TO_END   = 1;
    const unsigned short END_TO_END     = 2;
    const unsigned short END_TO_START   = 3;

    [ObjCLegacyUnnamedParameters, RaisesException, ImplementedAs=compareBoundaryPointsForBindings] short compareBoundaryPoints([Default=Undefined] optional unsigned short how, Range sourceRange);

    [RaisesException] void deleteContents();
    [RaisesException, NewObject] DocumentFragment extractContents();
    [RaisesException, NewObject] DocumentFragment cloneContents();
    [RaisesException] void insertNode(Node newNode);
    [RaisesException] void surroundContents(Node newParent);
    [NewObject] Range cloneRange();
    DOMString toString();

    void detach();

#if defined(LANGUAGE_JAVASCRIPT) || LANGUAGE_JAVASCRIPT
    // CSSOM View Module API extensions

    ClientRectList getClientRects();
    ClientRect getBoundingClientRect();
#endif

    // extensions

    [RaisesException] DocumentFragment createContextualFragment([Default=Undefined] optional DOMString html);

    // WebKit extensions

    [RaisesException] short compareNode(Node refNode);

    // CompareResults
    const unsigned short NODE_BEFORE           = 0;
    const unsigned short NODE_AFTER            = 1;
    const unsigned short NODE_BEFORE_AND_AFTER = 2;
    const unsigned short NODE_INSIDE           = 3;

    [RaisesException] short comparePoint(Node refNode, [Default=Undefined] optional long offset);
    [RaisesException] boolean intersectsNode(Node refNode);
    [RaisesException] boolean isPointInRange(Node refNode, [Default=Undefined] optional long offset);

    [RaisesException] void expand([Default=Undefined] optional DOMString unit);

#if !defined(LANGUAGE_JAVASCRIPT) || !LANGUAGE_JAVASCRIPT
    readonly attribute DOMString text;
#endif
};

