include(PlatformCocoa.cmake)

find_library(COCOA_LIBRARY Cocoa)
list(APPEND WTF_LIBRARIES
    ${COCOA_LIBRARY}
)

list(APPEND WTF_SOURCES
    mac/FileSystemMac.mm
)

WEBKIT_ADD_PREFIX_HEADER(WTF WTFPrefix.h PREFIX_LANGUAGES CXX OBJCXX PREFIX_NO_CODEGEN)
