include(PlatformCocoa.cmake)

find_library(UIKIT_LIBRARY UIKit)
list(APPEND WTF_LIBRARIES
    ${UIKIT_LIBRARY}
)

target_compile_options(WTF PRIVATE ${WEBKIT_PRIVATE_FRAMEWORKS_COMPILE_FLAG})

list(APPEND WTF_SOURCES
    ios/WebCoreThread.cpp
)

list(APPEND WTF_PUBLIC_HEADERS
    ios/WebCoreThread.h
)

WEBKIT_ADD_PREFIX_HEADER(WTF WTFPrefix.h PREFIX_LANGUAGES CXX OBJCXX PREFIX_NO_CODEGEN)
