partial interface TestGlobalObject {
    attribute DOMWindowConstructor DOMWindow;
    attribute DedicatedWorkerGlobalScopeConstructor DedicatedWorkerGlobalScope;
    attribute PaintWorkletGlobalScopeConstructor PaintWorkletGlobalScope;
    attribute ServiceWorkerGlobalScopeConstructor ServiceWorkerGlobalScope;
    attribute TestCEReactionsConstructor TestCEReactions;
    attribute TestCEReactionsStringifierConstructor TestCEReactionsStringifier;
    attribute TestCallTracerConstructor TestCallTracer;
    [Conditional=TEST_CONDITIONAL] attribute TestCallbackInterfaceConstructor TestCallbackInterface;
    attribute TestClassWithJSBuiltinConstructorConstructor TestClassWithJSBuiltinConstructor;
    attribute TestDOMJITConstructor TestDOMJIT;
    attribute TestDomainSecurityConstructor TestDomainSecurity;
    attribute TestEnabledBySettingConstructor TestEnabledBySetting;
    [EnabledForContext, SecureContext] attribute TestEnabledForContextConstructor TestEnabledForContext;
    attribute TestEventConstructorConstructor TestEventConstructor;
    attribute TestEventTargetConstructor TestEventTarget;
    attribute TestExceptionConstructor TestException;
    attribute TestGenerateIsReachableConstructor TestGenerateIsReachable;
    attribute TestGlobalObjectConstructor TestGlobalObject;
    attribute TestIndexedSetterNoIdentifierConstructor TestIndexedSetterNoIdentifier;
    attribute TestIndexedSetterThrowingExceptionConstructor TestIndexedSetterThrowingException;
    attribute TestIndexedSetterWithIdentifierConstructor TestIndexedSetterWithIdentifier;
    [Conditional=Condition1|Condition2] attribute TestInterfaceConstructor TestInterface;
    attribute TestInterfaceLeadingUnderscoreConstructor TestInterfaceLeadingUnderscore;
    attribute TestIterableConstructor TestIterable;
    attribute TestJSBuiltinConstructorConstructor TestJSBuiltinConstructor;
    attribute TestLegacyFactoryFunctionConstructor TestLegacyFactoryFunction;
    attribute TestLegacyFactoryFunctionLegacyFactoryFunctionConstructor Audio;
    attribute TestLegacyOverrideBuiltInsConstructor TestLegacyOverrideBuiltIns;
    attribute TestMapLikeConstructor TestMapLike;
    attribute TestNamedAndIndexedSetterNoIdentifierConstructor TestNamedAndIndexedSetterNoIdentifier;
    attribute TestNamedAndIndexedSetterThrowingExceptionConstructor TestNamedAndIndexedSetterThrowingException;
    attribute TestNamedAndIndexedSetterWithIdentifierConstructor TestNamedAndIndexedSetterWithIdentifier;
    attribute TestNamedDeleterNoIdentifierConstructor TestNamedDeleterNoIdentifier;
    attribute TestNamedDeleterThrowingExceptionConstructor TestNamedDeleterThrowingException;
    attribute TestNamedDeleterWithIdentifierConstructor TestNamedDeleterWithIdentifier;
    attribute TestNamedDeleterWithIndexedGetterConstructor TestNamedDeleterWithIndexedGetter;
    attribute TestNamedGetterCallWithConstructor TestNamedGetterCallWith;
    attribute TestNamedGetterNoIdentifierConstructor TestNamedGetterNoIdentifier;
    attribute TestNamedGetterWithIdentifierConstructor TestNamedGetterWithIdentifier;
    attribute TestNamedSetterNoIdentifierConstructor TestNamedSetterNoIdentifier;
    attribute TestNamedSetterThrowingExceptionConstructor TestNamedSetterThrowingException;
    attribute TestNamedSetterWithIdentifierConstructor TestNamedSetterWithIdentifier;
    attribute TestNamedSetterWithIndexedGetterConstructor TestNamedSetterWithIndexedGetter;
    attribute TestNamedSetterWithIndexedGetterAndSetterConstructor TestNamedSetterWithIndexedGetterAndSetter;
    attribute TestNamedSetterWithLegacyOverrideBuiltInsConstructor TestNamedSetterWithLegacyOverrideBuiltIns;
    attribute TestNamedSetterWithLegacyUnforgeablePropertiesConstructor TestNamedSetterWithLegacyUnforgeableProperties;
    attribute TestNamedSetterWithLegacyUnforgeablePropertiesAndLegacyOverrideBuiltInsConstructor TestNamedSetterWithLegacyUnforgeablePropertiesAndLegacyOverrideBuiltIns;
    [Conditional=ConditionDerived] attribute TestOperationConditionalConstructor TestOperationConditional;
    attribute TestOverloadedConstructorsWithSequenceConstructor TestOverloadedConstructorsWithSequence;
    attribute TestPluginInterfaceConstructor TestPluginInterface;
    attribute TestReadOnlyMapLikeConstructor TestReadOnlyMapLike;
    attribute TestReadOnlySetLikeConstructor TestReadOnlySetLike;
    attribute TestReportExtraMemoryCostConstructor TestReportExtraMemoryCost;
    attribute TestSerializationConstructor TestSerialization;
    attribute TestSerializationIndirectInheritanceConstructor TestSerializationIndirectInheritance;
    attribute TestSerializationInheritConstructor TestSerializationInherit;
    attribute TestSerializationInheritFinalConstructor TestSerializationInheritFinal;
    [Conditional=Condition1|Condition2] attribute TestSerializedScriptValueInterfaceConstructor TestSerializedScriptValueInterface;
    attribute TestSetLikeConstructor TestSetLike;
    attribute TestStringifierConstructor TestStringifier;
    attribute TestStringifierAnonymousOperationConstructor TestStringifierAnonymousOperation;
    attribute TestStringifierNamedOperationConstructor TestStringifierNamedOperation;
    attribute TestStringifierOperationImplementedAsConstructor TestStringifierOperationImplementedAs;
    attribute TestStringifierOperationNamedToStringConstructor TestStringifierOperationNamedToString;
    attribute TestStringifierReadOnlyAttributeConstructor TestStringifierReadOnlyAttribute;
    attribute TestStringifierReadWriteAttributeConstructor TestStringifierReadWriteAttribute;
    attribute TestTypedefsConstructor TestTypedefs;
    attribute WorkerGlobalScopeConstructor WorkerGlobalScope;
    attribute WorkletGlobalScopeConstructor WorkletGlobalScope;
};
