partial interface DOMWindow {
    attribute ExposedToWorkerAndWindowConstructor ExposedToWorkerAndWindow;
    attribute TestConditionallyReadWriteConstructor TestConditionallyReadWrite;
    attribute TestNodeConstructor TestNode;
    attribute TestObjConstructor TestObject;
    attribute TestPromiseRejectionEventConstructor TestPromiseRejectionEvent;
};
