partial interface DOMWindow {
    attribute DOMWindowConstructor DOMWindow;
    attribute ExposedToWorkerAndWindowConstructor ExposedToWorkerAndWindow;
    attribute TestConditionalIncludesConstructor TestConditionalIncludes;
    attribute TestConditionallyReadWriteConstructor TestConditionallyReadWrite;
    attribute TestDefaultToJSONConstructor TestDefaultToJSON;
    attribute TestDefaultToJSONFilteredByExposedConstructor TestDefaultToJSONFilteredByExposed;
    attribute TestEnabledBySettingConstructor TestEnabledBySetting;
    [EnabledForContext, SecureContext] attribute TestEnabledForContextConstructor TestEnabledForContext;
    [Conditional=Condition1|Condition2] attribute TestInterfaceConstructor TestInterface;
    attribute TestNodeConstructor TestNode;
    attribute TestObjConstructor TestObject;
    attribute TestPromiseRejectionEventConstructor TestPromiseRejectionEvent;
};
