partial interface ShadowRealmGlobalScope {
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute ExposedStarConstructor ExposedStar;
    attribute ShadowRealmGlobalScopeConstructor ShadowRealmGlobalScope;
};
