/*
 * Copyright (c) 1999 World Wide Web Consortium,
 * (Massachusetts Institute of Technology, Institut National de
 * Recherche en Informatique et en Automatique, Keio University). All
 * Rights Reserved. This program is distributed under the W3C's Software
 * Intellectual Property License. This program is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See W3C License http://www.w3.org/Consortium/Legal/ for more
 * details.
 */

module traversal
{
	// Introduced in DOM Level 2:
	interface NodeFilter {
		// Constants returned by acceptNode
		const short FILTER_ACCEPT	= 1;
		const short FILTER_REJECT	= 2;
		const short FILTER_SKIP		= 3;

		// Constants for whatToShow
		const unsigned long SHOW_ALL					= 0x0000FFFF;
		const unsigned long SHOW_ELEMENT				= 0x00000001;
		const unsigned long SHOW_ATTRIBUTE				= 0x00000002;
		const unsigned long SHOW_TEXT					= 0x00000004;
		const unsigned long SHOW_CDATA_SECTION			= 0x00000008;
		const unsigned long SHOW_ENTITY_REFERENCE		= 0x00000010;
		const unsigned long SHOW_ENTITY					= 0x00000020;
		const unsigned long SHOW_PROCESSING_INSTRUCTION	= 0x00000040;
		const unsigned long SHOW_COMMENT				= 0x00000080;
		const unsigned long SHOW_DOCUMENT				= 0x00000100;
		const unsigned long SHOW_DOCUMENT_TYPE			= 0x00000200;
		const unsigned long SHOW_DOCUMENT_FRAGMENT		= 0x00000400;
		const unsigned long SHOW_NOTATION				= 0x00000800;

		short acceptNode(in core::Node n);
	};
};
