/*
 * Copyright (c) 1999 World Wide Web Consortium,
 * (Massachusetts Institute of Technology, Institut National de
 * Recherche en Informatique et en Automatique, Keio University). All
 * Rights Reserved. This program is distributed under the W3C's Software
 * Intellectual Property License. This program is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See W3C License http://www.w3.org/Consortium/Legal/ for more
 * details.
 */

module traversal
{
	// Introduced in DOM Level 2:
	interface TreeWalker {
		readonly attribute long whatToShow;
		readonly attribute NodeFilter filter;
		readonly attribute boolean expandEntityReferences;
		attribute core::Node currentNode [raises(core::DOMException)];

		core::Node parentNode();

		core::Node firstChild();
		core::Node lastChild();

		core::Node previousSibling();
		core::Node nextSibling();

		core::Node previousNode();
		core::Node nextNode();
	};
};
