module ls
{
  interface LSParserFilter {
    // Constants returned by startElement and acceptNode
//    const short               FILTER_ACCEPT                  = 1;
//    const short               FILTER_REJECT                  = 2;
//    const short               FILTER_SKIP                    = 3;
//    const short               FILTER_INTERRUPT               = 4;
    unsigned short     startElement(in core::Element elementArg);
    unsigned short     acceptNode(in core::Node nodeArg);
    readonly attribute unsigned long   whatToShow;
  };
};
