module ls
{
  interface LSResourceResolver {
    LSInput            resolveResource(in DOMString type, 
                                       in DOMString namespaceURI, 
                                       in DOMString publicId, 
                                       in DOMString systemId, 
                                       in DOMString baseURI);
  };
};
