/*
 * Copyright (C) 2025 Samuel Weinig <sam@webkit.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// https://drafts.csswg.org/css-fonts-5/#cssfontfacedescriptors

typedef USVString CSSOMString;

[
    JSGenerateToNativeObject,
    Exposed=Window,
] interface CSSFontFaceDescriptors : CSSStyleDeclaration {
  attribute [LegacyNullToEmptyString] CSSOMString src;
  attribute [LegacyNullToEmptyString] CSSOMString fontFamily;
  attribute [LegacyNullToEmptyString] CSSOMString font-family;
  attribute [LegacyNullToEmptyString] CSSOMString fontStyle;
  attribute [LegacyNullToEmptyString] CSSOMString font-style;
  attribute [LegacyNullToEmptyString] CSSOMString fontWeight;
  attribute [LegacyNullToEmptyString] CSSOMString font-weight;
  attribute [LegacyNullToEmptyString] CSSOMString fontStretch;
  attribute [LegacyNullToEmptyString] CSSOMString font-stretch;
  attribute [LegacyNullToEmptyString] CSSOMString fontWidth;
  attribute [LegacyNullToEmptyString] CSSOMString font-width;
  // attribute [LegacyNullToEmptyString] CSSOMString fontSize;
  // attribute [LegacyNullToEmptyString] CSSOMString font-size;
  attribute [LegacyNullToEmptyString] CSSOMString sizeAdjust;
  attribute [LegacyNullToEmptyString] CSSOMString size-adjust;
  attribute [LegacyNullToEmptyString] CSSOMString unicodeRange;
  attribute [LegacyNullToEmptyString] CSSOMString unicode-range;
  attribute [LegacyNullToEmptyString] CSSOMString fontFeatureSettings;
  attribute [LegacyNullToEmptyString] CSSOMString font-feature-settings;
  // attribute [LegacyNullToEmptyString] CSSOMString fontVariationSettings;
  // attribute [LegacyNullToEmptyString] CSSOMString font-variation-settings;
  // attribute [LegacyNullToEmptyString] CSSOMString fontNamedInstance;
  // attribute [LegacyNullToEmptyString] CSSOMString font-named-instance;
  attribute [LegacyNullToEmptyString] CSSOMString fontDisplay;
  attribute [LegacyNullToEmptyString] CSSOMString font-display;
  // attribute [LegacyNullToEmptyString] CSSOMString fontLanguageOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString font-language-override;
  // attribute [LegacyNullToEmptyString] CSSOMString ascentOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString ascent-override;
  // attribute [LegacyNullToEmptyString] CSSOMString descentOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString descent-override;
  // attribute [LegacyNullToEmptyString] CSSOMString lineGapOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString line-gap-override;
  // attribute [LegacyNullToEmptyString] CSSOMString superscriptPositionOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString superscript-position-override;
  // attribute [LegacyNullToEmptyString] CSSOMString subscriptPositionOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString subscript-position-override;
  // attribute [LegacyNullToEmptyString] CSSOMString superscriptSizeOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString superscript-size-override;
  // attribute [LegacyNullToEmptyString] CSSOMString subscriptSizeOverride;
  // attribute [LegacyNullToEmptyString] CSSOMString subscript-size-override;
};
