module xpointer
{
	interface [nodptr] XPointerEvaluator {
		XPointerExpression createXPointer(in core::DOMString string,
										  in core::Node relatedNode);

		XPointerResult evaluateXPointer(in core::DOMString xpointer,
										in core::Node relatedNode);
	};
};
