module xpointer
{
	interface XPointerResult {
		const unsigned short NO_MATCH = 1;
		const unsigned short SINGLE_NODE = 2;

		attribute core::Node singleNodeValue;
		attribute unsigned short resultType;
	};
};
