#!/bin/sh -e

eval ARCHS=(${ARCHS})
eval HEADER_SEARCH_PATHS=(${BUILT_PRODUCTS_DIR} ${HEADER_SEARCH_PATHS} ${SYSTEM_HEADER_SEARCH_PATHS})
eval FRAMEWORK_SEARCH_PATHS=(${BUILT_PRODUCTS_DIR} ${FRAMEWORK_SEARCH_PATHS} ${SYSTEM_FRAMEWORK_SEARCH_PATHS})
eval GCC_PREPROCESSOR_DEFINITIONS=(${GCC_PREPROCESSOR_DEFINITIONS})

CFLAGS=(
    -isysroot "${SDKROOT}"
    -target ${ARCHS[0]}-${LLVM_TARGET_TRIPLE_VENDOR}-${LLVM_TARGET_TRIPLE_OS_VERSION}${LLVM_TARGET_TRIPLE_SUFFIX}
    ${FRAMEWORK_SEARCH_PATHS[@]/#/-F}
    ${HEADER_SEARCH_PATHS[@]/#/-I}
    ${GCC_PREPROCESSOR_DEFINITIONS[@]/#/-D}
)
if [ "${USE_SYSTEM_CONTENT_PATH}" = YES ]; then
    CFLAGS+=(-DUSE_SYSTEM_CONTENT_PATH=1 -DSYSTEM_CONTENT_PATH="${SYSTEM_CONTENT_PATH}")
fi

grep -o '^[^;]*' "${INPUT_FILE_PATH}" | clang -E -P -w -DRELEASE_WITHOUT_OPTIMIZATIONS -MD -MF "${DERIVED_FILES_DIR}/${INPUT_FILE_PATH}.d" ${CFLAGS[@]} -include "wtf/Platform.h" - > "${SCRIPT_OUTPUT_FILE_0}"

