#!/usr/bin/env bash

source "$(dirname "$0")/../../glib/dependencies/apt"

# If the package $1 is available, prints it. Otherwise prints $2.
# Useful for handling when a package is renamed on new versions of Debian/Ubuntu.
function aptIfElse {
    if apt-cache show $1 &>/dev/null; then
        echo $1
    else
        echo $2
    fi
}

PACKAGES+=(
    # These are dependencies necessary for building WebKitGTK.
    geoclue-2.0
    gnome-common
    libatk1.0-dev
    libedit-dev
    libenchant-dev
    libfaad-dev
    libffi-dev
    $(aptIfElse libgcrypt20-dev libgcrypt11-dev)
    libgirepository1.0-dev
    libgl1-mesa-dev
    libgl1-mesa-glx
    libgtk-3-dev
    libgudev-1.0-dev
    libhyphen-dev
    libmount-dev
    libmpg123-dev
    libnotify-dev
    libopus-dev
    libpango1.0-dev
    libpulse-dev
    librsvg2-dev
    libsecret-1-dev
    libsoup2.4-dev
    libsrtp2-dev
    libtheora-dev
    libupower-glib-dev
    libvorbis-dev
    libvpx-dev
    libwayland-dev
    libxcomposite-dev
    libxt-dev
    libxtst-dev
    nasm
    xfonts-utils

    # These are dependencies necessary for running tests.
    cups-daemon
    dbus-x11
    hunspell
    hunspell-en-gb
    hunspell-en-us
    python-psutil
    python-yaml
    weston
    xvfb

    # These are dependencies necessary for building the jhbuild.
    bison
    flex
    gobject-introspection
    icon-naming-utils
    libcroco3-dev
    libcups2-dev
    libdrm-dev
    libepoxy-dev
    libevdev-dev
    libgbm-dev
    libgnutls28-dev
    libgpg-error-dev
    libinput-dev
    libjson-glib-dev
    libmtdev-dev
    libp11-kit-dev
    libpciaccess-dev
    libssl-dev
    libtiff5-dev
    libudev-dev
    libunistring-dev
    libv4l-dev
    libxcb-composite0-dev
    libxcb-xfixes0-dev
    libxfont2
    libxfont-dev
    libxkbcommon-x11-dev
    libxkbfile-dev
    python-dev
    ragel
    x11proto-bigreqs-dev
    x11proto-composite-dev
    x11proto-gl-dev
    x11proto-input-dev
    x11proto-randr-dev
    x11proto-resource-dev
    x11proto-scrnsaver-dev
    x11proto-video-dev
    x11proto-xcmisc-dev
    x11proto-xf86dri-dev
    xtrans-dev
    xutils-dev
)
