#!/usr/bin/env bash

PACKAGES=(
    autoconf
    automake
    cmake
    enchant
    gettext
    gobject-introspection
    intltool
    itstool
    libcroco
    libgcrypt
    libgpg-error
    libtasn1
    libtiff
    libtool
    little-cms2
    ninja
    pango
    pkg-config
    sqlite
    webp
    xz
)
