// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include "RenderStyleProperties.h"
#include "StyleComputedStyle+ConstructionInlines.h"

namespace WebCore {

inline RenderStyleProperties::RenderStyleProperties(RenderStyleProperties&&) = default;
inline RenderStyleProperties& RenderStyleProperties::operator=(RenderStyleProperties&&) = default;

inline RenderStyleProperties::RenderStyleProperties(CreateDefaultStyleTag)
    : m_computedStyle(Style::ComputedStyle::CreateDefaultStyle)
{
}

inline RenderStyleProperties::RenderStyleProperties(const RenderStyleProperties& other, CloneTag)
    : m_computedStyle(other.m_computedStyle, Style::ComputedStyle::Clone)
{
}

inline RenderStyleProperties::RenderStyleProperties(RenderStyleProperties& a, RenderStyleProperties&& b)
    : m_computedStyle(a.m_computedStyle, WTF::move(b.m_computedStyle))
{
}

} // namespace WebCore

