/*
 * Copyright (C) 2022 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

// FIXME: Support Serializable and Transferable.
[
    ActiveDOMObject,
    Conditional=WEB_CODECS,
    EnabledBySetting=WebCodecsEnabled,
    Exposed=(Window,DedicatedWorker),
    InterfaceName=VideoEncoder,
] interface WebCodecsVideoEncoder : EventTarget {
    [CallWith=CurrentScriptExecutionContext] constructor(WebCodecsVideoEncoderInit init);

    readonly attribute WebCodecsCodecState state;
    readonly attribute unsigned long encodeQueueSize;
    attribute EventHandler ondequeue;

    undefined configure(WebCodecsVideoEncoderConfig config);
    undefined encode(WebCodecsVideoFrame frame, optional WebCodecsVideoEncoderEncodeOptions options = {});
    Promise<undefined> flush();
    undefined reset();
    undefined close();

    static Promise<WebCodecsVideoEncoderSupport> isConfigSupported(WebCodecsVideoEncoderConfig config);
};

[
    Conditional=WEB_CODECS,
] dictionary WebCodecsVideoEncoderInit {
    required WebCodecsEncodedVideoChunkOutputCallback output;
    required WebCodecsErrorCallback error;
};
