/*
 * Copyright (c) 2000 World Wide Web Consortium,
 * (Massachusetts Institute of Technology, Institut National de
 * Recherche en Informatique et en Automatique, Keio University). All
 * Rights Reserved. This program is distributed under the W3C's Software
 * Intellectual Property License. This program is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.
 * See W3C License http://www.w3.org/Consortium/Legal/ for more details.
 */

// File: http://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.idl

module css
{
	// Introduced in DOM Level 2:
	interface CSS2Properties {
		attribute core::DOMString azimuth;
		attribute core::DOMString background;
		attribute core::DOMString backgroundAttachment;
		attribute core::DOMString backgroundColor;
		attribute core::DOMString backgroundImage;
		attribute core::DOMString backgroundPosition;
		attribute core::DOMString backgroundRepeat;
		attribute core::DOMString border;
		attribute core::DOMString borderCollapse;
		attribute core::DOMString borderColor;
		attribute core::DOMString borderSpacing;
		attribute core::DOMString borderStyle;
		attribute core::DOMString borderTop;
		attribute core::DOMString borderRight;
		attribute core::DOMString borderBottom;
		attribute core::DOMString borderLeft;
		attribute core::DOMString borderTopColor;
		attribute core::DOMString borderRightColor;
		attribute core::DOMString borderBottomColor;
		attribute core::DOMString borderLeftColor;
		attribute core::DOMString borderTopStyle;
		attribute core::DOMString borderRightStyle;
		attribute core::DOMString borderBottomStyle;
		attribute core::DOMString borderLeftStyle;
		attribute core::DOMString borderTopWidth;
		attribute core::DOMString borderRightWidth;
		attribute core::DOMString borderBottomWidth;
		attribute core::DOMString borderLeftWidth;
		attribute core::DOMString borderWidth;
		attribute core::DOMString bottom;
		attribute core::DOMString captionSide;
		attribute core::DOMString clear;
		attribute core::DOMString clip;
		attribute core::DOMString color;
		attribute core::DOMString content;
		attribute core::DOMString counterIncrement;
		attribute core::DOMString counterReset;
		attribute core::DOMString cue;
		attribute core::DOMString cueAfter;
		attribute core::DOMString cueBefore;
		attribute core::DOMString cursor;
		attribute core::DOMString direction;
		attribute core::DOMString display;
		attribute core::DOMString elevation;
		attribute core::DOMString emptyCells;
		attribute core::DOMString cssFloat;
		attribute core::DOMString font;
		attribute core::DOMString fontFamily;
		attribute core::DOMString fontSize;
		attribute core::DOMString fontSizeAdjust;
		attribute core::DOMString fontStretch;
		attribute core::DOMString fontStyle;
		attribute core::DOMString fontVariant;
		attribute core::DOMString fontWeight;
		attribute core::DOMString height;
		attribute core::DOMString left;
		attribute core::DOMString letterSpacing;
		attribute core::DOMString lineHeight;
		attribute core::DOMString listStyle;
		attribute core::DOMString listStyleImage;
		attribute core::DOMString listStylePosition;
		attribute core::DOMString listStyleType;
		attribute core::DOMString margin;
		attribute core::DOMString marginTop;
		attribute core::DOMString marginRight;
		attribute core::DOMString marginBottom;
		attribute core::DOMString marginLeft;
		attribute core::DOMString markerOffset;
		attribute core::DOMString marks;
		attribute core::DOMString maxHeight;
		attribute core::DOMString maxWidth;
		attribute core::DOMString minHeight;
		attribute core::DOMString minWidth;
		attribute core::DOMString orphans;
		attribute core::DOMString outline;
		attribute core::DOMString outlineColor;
		attribute core::DOMString outlineStyle;
		attribute core::DOMString outlineWidth;
		attribute core::DOMString overflow;
		attribute core::DOMString padding;
		attribute core::DOMString paddingTop;
		attribute core::DOMString paddingRight;
		attribute core::DOMString paddingBottom;
		attribute core::DOMString paddingLeft;
		attribute core::DOMString page;
		attribute core::DOMString pageBreakAfter;
		attribute core::DOMString pageBreakBefore;
		attribute core::DOMString pageBreakInside;
		attribute core::DOMString pause;
		attribute core::DOMString pauseAfter;
		attribute core::DOMString pauseBefore;
		attribute core::DOMString pitch;
		attribute core::DOMString pitchRange;
		attribute core::DOMString playDuring;
		attribute core::DOMString position;
		attribute core::DOMString quotes;
		attribute core::DOMString richness;
		attribute core::DOMString right;
		attribute core::DOMString size;
		attribute core::DOMString speak;
		attribute core::DOMString speakHeader;
		attribute core::DOMString speakNumeral;
		attribute core::DOMString speakPunctuation;
		attribute core::DOMString speechRate;
		attribute core::DOMString stress;
		attribute core::DOMString tableLayout;
		attribute core::DOMString textAlign;
		attribute core::DOMString textDecoration;
		attribute core::DOMString textIndent;
		attribute core::DOMString textShadow;
		attribute core::DOMString textTransform;
		attribute core::DOMString top;
		attribute core::DOMString unicodeBidi;
		attribute core::DOMString verticalAlign;
		attribute core::DOMString visibility;
		attribute core::DOMString voiceFamily;
		attribute core::DOMString volume;
		attribute core::DOMString whiteSpace;
		attribute core::DOMString widows;
		attribute core::DOMString width;
		attribute core::DOMString wordSpacing;
		attribute core::DOMString zIndex;
	};
};
