/*
 * Copyright (c) 2000 World Wide Web Consortium,
 * (Massachusetts Institute of Technology, Institut National de
 * Recherche en Informatique et en Automatique, Keio University). All
 * Rights Reserved. This program is distributed under the W3C's Software
 * Intellectual Property License. This program is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.
 * See W3C License http://www.w3.org/Consortium/Legal/ for more details.
 */

// File: http://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.idl

module css
{
	// Introduced in DOM Level 2:
	interface CSSRule {
		// RuleType
		const unsigned short UNKNOWN_RULE	= 0;
		const unsigned short STYLE_RULE		= 1;
		const unsigned short CHARSET_RULE	= 2;
		const unsigned short IMPORT_RULE	= 3;
		const unsigned short MEDIA_RULE		= 4;
		const unsigned short FONT_FACE_RULE	= 5;
		const unsigned short PAGE_RULE		= 6;

		readonly attribute unsigned short type;
		attribute core::DOMString cssText [raises(core::DOMException)];
		readonly attribute CSSStyleSheet parentStyleSheet;
		readonly attribute CSSRule parentRule;
	};
};
