/*
 * Copyright (C) 2026 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * WebKit-supplied <Availability.h> stub. Companion of <os/availability.h>;
 * see that file for the rationale. All public availability macros expand
 * to nothing; the SDK's AvailabilityInternal*.h and AvailabilityVersions.h
 * are still used for version constants.
 */

#pragma once

#define __API_TO_BE_DEPRECATED 100000

#define __API_TO_BE_DEPRECATED_MACOS 100000
#define __API_TO_BE_DEPRECATED_MACOSAPPLICATIONEXTENSION 100000

#define __API_TO_BE_DEPRECATED_IOS 100000
#define __API_TO_BE_DEPRECATED_IOSAPPLICATIONEXTENSION 100000

#define __API_TO_BE_DEPRECATED_MACCATALYST 100000
#define __API_TO_BE_DEPRECATED_MACCATALYSTAPPLICATIONEXTENSION 100000

#define __API_TO_BE_DEPRECATED_WATCHOS 100000
#define __API_TO_BE_DEPRECATED_WATCHOSAPPLICATIONEXTENSION 100000

#define __API_TO_BE_DEPRECATED_TVOS 100000
#define __API_TO_BE_DEPRECATED_TVOSAPPLICATIONEXTENSION 100000

#define __API_TO_BE_DEPRECATED_BRIDGEOS 100000

#define __API_TO_BE_DEPRECATED_DRIVERKIT 100000

#define __API_TO_BE_DEPRECATED_VISIONOS 100000
#define __API_TO_BE_DEPRECATED_VISIONOSAPPLICATIONEXTENSION 100000

#define __API_TO_BE_DEPRECATED_EXCLAVEKIT 100000

#define __API_TO_BE_DEPRECATED_KERNELKIT 100000

#ifndef API_TO_BE_DEPRECATED_XROS
#define API_TO_BE_DEPRECATED_XROS 100000
#endif

#include <AvailabilityInternal.h>
#include <AvailabilityInternalLegacy.h>
#if __has_include(<AvailabilityInternalPrivate.h>)
#include <AvailabilityInternalPrivate.h>
#endif

#define __OSX_AVAILABLE_STARTING(_osx, _ios)
#define __OSX_AVAILABLE_BUT_DEPRECATED(_osxIntro, _osxDep, _iosIntro, _iosDep)
#define __OSX_AVAILABLE_BUT_DEPRECATED_MSG(_osxIntro, _osxDep, _iosIntro, _iosDep, _msg)

#define __OS_AVAILABILITY(_target, _availability)
#define __OS_AVAILABILITY_MSG(_target, _availability, _msg)

#define __OSX_EXTENSION_UNAVAILABLE(_msg)
#define __IOS_EXTENSION_UNAVAILABLE(_msg)
#define __OS_EXTENSION_UNAVAILABLE(_msg)

#define __OSX_UNAVAILABLE
#define __OSX_AVAILABLE(_vers)
#define __OSX_DEPRECATED(_start, _dep, _msg)

#define __IOS_UNAVAILABLE
#define __IOS_PROHIBITED
#define __IOS_AVAILABLE(_vers)
#define __IOS_DEPRECATED(_start, _dep, _msg)

#define __TVOS_UNAVAILABLE
#define __TVOS_PROHIBITED
#define __TVOS_AVAILABLE(_vers)
#define __TVOS_DEPRECATED(_start, _dep, _msg)

#define __WATCHOS_UNAVAILABLE
#define __WATCHOS_PROHIBITED
#define __WATCHOS_AVAILABLE(_vers)
#define __WATCHOS_DEPRECATED(_start, _dep, _msg)

#define __SWIFT_UNAVAILABLE
#define __SWIFT_UNAVAILABLE_MSG(_msg)

#define __API_AVAILABLE(...)
#define __API_AVAILABLE_BEGIN(...)
#define __API_AVAILABLE_END

// Deprecations are not stubbed out because they have an effect on how Swift
// imports C APIs, namely on its enum case naming heuristic.
#define __API_DEPRECATED(...) __API_DEPRECATED_MSG_GET_MACRO_93585900(__VA_ARGS__,__API_DEPRECATED_MSG15,__API_DEPRECATED_MSG14,__API_DEPRECATED_MSG13,__API_DEPRECATED_MSG12,__API_DEPRECATED_MSG11,__API_DEPRECATED_MSG10,__API_DEPRECATED_MSG9,__API_DEPRECATED_MSG8,__API_DEPRECATED_MSG7,__API_DEPRECATED_MSG6,__API_DEPRECATED_MSG5,__API_DEPRECATED_MSG4,__API_DEPRECATED_MSG3,__API_DEPRECATED_MSG2,__API_DEPRECATED_MSG1,__API_DEPRECATED_MSG0,0,0)(__VA_ARGS__)
#define __API_DEPRECATED_WITH_REPLACEMENT(...) __API_DEPRECATED_REP_GET_MACRO_93585900(__VA_ARGS__,__API_DEPRECATED_REP15,__API_DEPRECATED_REP14,__API_DEPRECATED_REP13,__API_DEPRECATED_REP12,__API_DEPRECATED_REP11,__API_DEPRECATED_REP10,__API_DEPRECATED_REP9,__API_DEPRECATED_REP8,__API_DEPRECATED_REP7,__API_DEPRECATED_REP6,__API_DEPRECATED_REP5,__API_DEPRECATED_REP4,__API_DEPRECATED_REP3,__API_DEPRECATED_REP2,__API_DEPRECATED_REP1,__API_DEPRECATED_REP0,0,0)(__VA_ARGS__)

#define __API_DEPRECATED_BEGIN(...) _Pragma("clang attribute push") __API_DEPRECATED_BEGIN_GET_MACRO_93585900(__VA_ARGS__,__API_DEPRECATED_BEGIN15,__API_DEPRECATED_BEGIN14,__API_DEPRECATED_BEGIN13,__API_DEPRECATED_BEGIN12,__API_DEPRECATED_BEGIN11,__API_DEPRECATED_BEGIN10,__API_DEPRECATED_BEGIN9,__API_DEPRECATED_BEGIN8,__API_DEPRECATED_BEGIN7,__API_DEPRECATED_BEGIN6,__API_DEPRECATED_BEGIN5,__API_DEPRECATED_BEGIN4,__API_DEPRECATED_BEGIN3,__API_DEPRECATED_BEGIN2,__API_DEPRECATED_BEGIN1,__API_DEPRECATED_BEGIN0,0,0)(__VA_ARGS__)
#define __API_DEPRECATED_END _Pragma("clang attribute pop")

#define __API_DEPRECATED_WITH_REPLACEMENT_BEGIN(...) _Pragma("clang attribute push") __API_DEPRECATED_WITH_REPLACEMENT_BEGIN_GET_MACRO_93585900(__VA_ARGS__,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN15,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN14,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN13,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN12,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN11,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN10,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN9,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN8,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN7,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN6,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN5,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN4,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN3,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN2,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN1,__API_DEPRECATED_WITH_REPLACEMENT_BEGIN0,0,0)(__VA_ARGS__)
#define __API_DEPRECATED_WITH_REPLACEMENT_END _Pragma("clang attribute pop")

#define __API_OBSOLETED(...)
#define __API_OBSOLETED_BEGIN(...)
#define __API_OBSOLETED_END
#define __API_OBSOLETED_WITH_REPLACEMENT(...)
#define __API_OBSOLETED_WITH_REPLACEMENT_BEGIN(...)
#define __API_OBSOLETED_WITH_REPLACEMENT_END

#define __API_UNAVAILABLE(...)
#define __API_UNAVAILABLE_BEGIN(...)
#define __API_UNAVAILABLE_END

#define __SPI_AVAILABLE(...)
#define __SPI_AVAILABLE_BEGIN(...)
#define __SPI_AVAILABLE_END

#define __SPI_DEPRECATED(...)
#define __SPI_DEPRECATED_WITH_REPLACEMENT(...)

/*
 * Hash macro at end of file so the SDK's hash-collision check in
 * AvailabilityInternal.h sees a matching value.
 */
#ifndef __AVAILABILITY_VERSIONS_VERSION_HASH
#define __AVAILABILITY_VERSIONS_VERSION_HASH 93585900U
#define __AVAILABILITY_VERSIONS_VERSION_STRING "WebKitAvailabilityOverlay"
#define __AVAILABILITY_FILE "Availability.h"
#elif __AVAILABILITY_VERSIONS_VERSION_HASH != 93585900U
#pragma GCC error "WebKit AvailabilityOverlay hash mismatch with SDK AvailabilityVersions; update WebKitLibraries/AvailabilityOverlay/usr/include/Availability.h"
#endif
