/*
 * Copyright (C) 2023 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#import "config.h"

#if HAVE(CONTACTS)

#import <Contacts/Contacts.h>
#import <wtf/SoftLinking.h>

SOFT_LINK_FRAMEWORK_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, PAL_EXPORT)
SOFT_LINK_CLASS_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContact, PAL_EXPORT)
SOFT_LINK_CLASS_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNLabeledValue, PAL_EXPORT)
SOFT_LINK_CLASS_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNPhoneNumber, PAL_EXPORT)
SOFT_LINK_CLASS_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNPostalAddress, PAL_EXPORT)
SOFT_LINK_CLASS_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNMutableContact, PAL_EXPORT)
SOFT_LINK_CLASS_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNMutablePostalAddress, PAL_EXPORT)
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactDepartmentNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactFamilyNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactGivenNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactJobTitleKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactMiddleNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactNamePrefixKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactNameSuffixKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactNicknameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactNoteKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactOrganizationNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPhoneticFamilyNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPhoneticGivenNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPhoneticMiddleNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPhoneticOrganizationNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPreviousFamilyNameKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactBirthdayKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactNonGregorianBirthdayKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPhoneNumbersKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactEmailAddressesKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactPostalAddressesKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactDatesKey, NSString *, PAL_EXPORT);
SOFT_LINK_CONSTANT_FOR_SOURCE_WITH_EXPORT(PAL, Contacts, CNContactUrlAddressesKey, NSString *, PAL_EXPORT);

#endif // HAVE(CONTACTS)
