/*
 * Copyright (C) 2024 Apple, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

// https://immersive-web.github.io/layers/#xrwebglsubimagetype
[
    Conditional=WEBXR_LAYERS,
    EnabledBySetting=WebXRLayersAPIEnabled,
    Exposed=Window
] interface XRWebGLSubImage : XRSubImage {
    [SameObject] readonly attribute WebGLTexture colorTexture;
    [SameObject] readonly attribute WebGLTexture? depthStencilTexture;
    [SameObject] readonly attribute WebGLTexture? motionVectorTexture;

    readonly attribute unsigned long? imageIndex;
    readonly attribute unsigned long colorTextureWidth;
    readonly attribute unsigned long colorTextureHeight;
    readonly attribute unsigned long? depthStencilTextureWidth;
    readonly attribute unsigned long? depthStencilTextureHeight;
    readonly attribute unsigned long? motionVectorTextureWidth;
    readonly attribute unsigned long? motionVectorTextureHeight;
};
