/*
 * Copyright (C) 2014 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

export default [
    {
        ignores: [
            "Localizations/**",
            "Tools/**",
            "UserInterface/External/**",
            "UserInterface/Protocol/Legacy/**",
            "**/*.min.js",
        ],
    },
    {
        files: ["**/*.js"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                // Browser
                "AbortController": "readonly",
                "alert": "readonly",
                "atob": "readonly",
                "Blob": "readonly",
                "btoa": "readonly",
                "cancelAnimationFrame": "readonly",
                "CanvasGradient": "readonly",
                "CanvasPattern": "readonly",
                "CanvasRenderingContext2D": "readonly",
                "clearInterval": "readonly",
                "clearTimeout": "readonly",
                "console": "readonly",
                "createImageBitmap": "readonly",
                "CSS": "readonly",
                "CSSPrimitiveValue": "writable",
                "document": "readonly",
                "DocumentFragment": "readonly",
                "DOMMatrix": "readonly",
                "DOMParser": "readonly",
                "Element": "readonly",
                "Event": "readonly",
                "event": "readonly",
                "Exception": "writable",
                "File": "readonly",
                "FileList": "readonly",
                "FileReader": "readonly",
                "getComputedStyle": "readonly",
                "HTMLCanvasElement": "readonly",
                "HTMLCollection": "readonly",
                "HTMLDocument": "readonly",
                "HTMLElement": "readonly",
                "HTMLIFrameElement": "readonly",
                "HTMLImageElement": "readonly",
                "HTMLInputElement": "readonly",
                "HTMLProgressElement": "readonly",
                "HTMLTextAreaElement": "readonly",
                "Image": "readonly",
                "ImageBitmap": "readonly",
                "ImageBitmapRenderingContext": "readonly",
                "ImageData": "readonly",
                "importScripts": "writable",
                "KeyboardEvent": "readonly",
                "MouseEvent": "readonly",
                "navigator": "readonly",
                "Node": "readonly",
                "OffscreenCanvasRenderingContext2D": "readonly",
                "Path2D": "readonly",
                "performance": "readonly",
                "queueMicrotask": "readonly",
                "requestAnimationFrame": "readonly",
                "self": "writable",
                "setInterval": "readonly",
                "setTimeout": "readonly",
                "SQLError": "writable",
                "Text": "readonly",
                "URL": "readonly",
                "WebGL2RenderingContext": "readonly",
                "WebGLRenderingContext": "readonly",
                "WebKitPoint": "writable",
                "WebSocket": "readonly",
                "window": "readonly",
                "Worker": "readonly",
                "XPathResult": "readonly",

                // External
                "CodeMirror": "writable",
                "esprima": "writable",
                "THREE": "writable",

                // Web Inspector
                "absoluteURL": "writable",
                "appendWebInspectorConsoleEvaluationSourceURL": "writable",
                "appendWebInspectorSourceURL": "writable",
                "AsyncTestSuite": "writable",
                "clamp": "writable",
                "createCodeMirrorColorTextMarkers": "writable",
                "createCodeMirrorCubicBezierTimingFunctionTextMarkers": "writable",
                "createCodeMirrorGradientTextMarkers": "writable",
                "createCodeMirrorLinearTimingFunctionTextMarkers": "writable",
                "createCodeMirrorSpringTimingFunctionTextMarkers": "writable",
                "createCodeMirrorStepsTimingFunctionTextMarkers": "writable",
                "createSVGElement": "writable",
                "CSSDocumentation": "writable",
                "CSSFormatter": "writable",
                "Debouncer": "writable",
                "doubleQuotedString": "writable",
                "ellipsis": "writable",
                "emDash": "writable",
                "enDash": "writable",
                "EsprimaFormatter": "writable",
                "ESTreeWalker": "writable",
                "figureDash": "writable",
                "Formatter": "writable",
                "FormatterContentBuilder": "writable",
                "FormatterWorker": "writable",
                "FrontendTestHarness": "writable",
                "handleInternalException": "writable",
                "handlePromiseException": "writable",
                "HeapSnapshot": "writable",
                "HeapSnapshotDiff": "writable",
                "HeapSnapshotWorker": "writable",
                "HTMLFormatter": "writable",
                "HTMLParser": "writable",
                "HTMLTreeBuilderFormatter": "writable",
                "insertionIndexForObjectInListSortedByFunction": "writable",
                "insertObjectIntoSortedArray": "writable",
                "InspectorBackend": "writable",
                "InspectorBackendClass": "writable",
                "InspectorFrontendAPI": "writable",
                "InspectorFrontendHost": "writable",
                "InspectorProtocol": "writable",
                "InspectorTest": "writable",
                "isECMAScriptLineTerminator": "writable",
                "isECMAScriptWhitespace": "writable",
                "isEmptyObject": "writable",
                "isEnterKey": "writable",
                "isFunctionStringNativeCode": "writable",
                "isTextLikelyMinified": "writable",
                "isWebInspectorBootstrapScript": "writable",
                "isWebInspectorConsoleEvaluationScript": "writable",
                "isWebInspectorInternalScript": "writable",
                "isWebKitInjectedScript": "writable",
                "isWebKitInternalScript": "writable",
                "IterableWeakSet": "writable",
                "JSFormatter": "writable",
                "Multimap": "writable",
                "multiplicationSign": "writable",
                "nullish": "writable",
                "parseDataURL": "writable",
                "parseLocationQueryParameters": "writable",
                "parseMIMEType": "writable",
                "parseQueryString": "writable",
                "parseSecurityOrigin": "writable",
                "parseURL": "writable",
                "ProtocolTest": "writable",
                "ProtocolTestHarness": "writable",
                "relativePath": "writable",
                "removeURLFragment": "writable",
                "resolveDotsInPath": "writable",
                "retryUntil": "writable",
                "simpleGlobStringToRegExp": "writable",
                "SyncTestSuite": "writable",
                "TestHarness": "writable",
                "TestSuite": "writable",
                "Throttler": "writable",
                "timestamp": "writable",
                "WebInspectorAudit": "writable",
                "WebKitAdditions": "writable",
                "WI": "writable",
                "xor": "writable",
                "zeroWidthSpace": "writable",
            },
        },
        rules: {
            "consistent-return": 0,
            "constructor-super": "error",
            "curly": 0,
            "dot-notation": 0,
            "eqeqeq": 2,
            "for-direction": "error",
            "getter-return": "error",
            "new-cap": 0,
            "new-parens": 0,
            "no-async-promise-executor": "error",
            "no-case-declarations": "error",
            "no-class-assign": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": "error",
            "no-console": 0,
            "no-const-assign": "error",
            "no-constant-binary-expression": "error",
            "no-constant-condition": 0,
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-delete-var": "error",
            "no-dupe-args": "error",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-empty": [2, {"allowEmptyCatch": true}],
            "no-empty-character-class": "error",
            "no-empty-pattern": "error",
            "no-empty-static-block": "error",
            "no-ex-assign": "error",
            "no-extra-bind": 2,
            "no-extra-boolean-cast": "error",
            "no-fallthrough": [2, {"allowEmptyCase": true}],
            "no-func-assign": "error",
            "no-global-assign": 2,
            "no-import-assign": "error",
            "no-inner-declarations": 0,
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-loss-of-precision": "error",
            "no-misleading-character-class": "error",
            "no-new": 0,
            "no-new-native-nonconstructor": "error",
            "no-nonoctal-decimal-escape": "error",
            "no-obj-calls": "error",
            "no-octal": "error",
            "no-proto": 0,
            "no-prototype-builtins": 0,
            "no-redeclare": 0,
            "no-regex-spaces": "error",
            "no-return-assign": 2,
            "no-self-assign": "error",
            "no-self-compare": 2,
            "no-setter-return": "error",
            "no-shadow": 0,
            "no-shadow-restricted-names": "error",
            "no-sparse-arrays": "error",
            "no-this-before-super": "error",
            "no-undef": 2,
            "no-underscore-dangle": 0,
            "no-unexpected-multiline": "error",
            "no-unreachable": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-expressions": 2,
            "no-unused-labels": "error",
            "no-unused-private-class-members": "error",
            "no-unused-vars": [2, {"vars": "local", "args": "none", "destructuredArrayIgnorePattern": ".*"}],
            "no-use-before-define": 0,
            "no-useless-backreference": "error",
            "no-useless-catch": "error",
            "no-useless-escape": ["error", {"allowRegexCharacters": ["["]}],
            "no-with": "error",
            "require-yield": "error",
            "strict": 0,
            "use-isnan": "error",
            "valid-typeof": 2,
        },
    },
];
