(module
  (func (export "test") (param i32) (result i32)
    (block (result i32)
      (br_if 0
        (i32.const 2)
        (if (result i32) (local.get 0)
          (then (i32.const 1))
          (else (i32.const 0))
        )
      )
      (return (i32.const 3))
    )
  )
  (func (export "checkResult") (param i32) (result i32)
     (i32.eq (i32.const 3) (local.get 0))
  )
)
