set(TEST_LIBRARY_DIR ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/WPEAPITests)
set(TEST_BINARY_DIR ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/TestWebKitAPI/WPE)

file(REMOVE_RECURSE ${TEST_LIBRARY_DIR})
file(MAKE_DIRECTORY ${TEST_LIBRARY_DIR})

file(REMOVE_RECURSE ${TEST_BINARY_DIR})
file(MAKE_DIRECTORY ${TEST_BINARY_DIR})

list(APPEND WebKitGLibAPITests_SOURCES
    ${TOOLS_DIR}/TestWebKitAPI/glib/WebKitGLib/wpe/WebViewTestWPE.cpp
)

list(APPEND WebKitGLibAPITests_INCLUDE_DIRECTORIES
    ${DERIVED_SOURCES_WPE_API_DIR}
    ${FORWARDING_HEADERS_WPE_DIR}
    ${FORWARDING_HEADERS_WPE_DOM_DIR}
    ${FORWARDING_HEADERS_WPE_EXTENSION_DIR}
)

list(APPEND WebKitGLibAPITestsCore_LIBRARIES
    WebKit::WPEToolingBackends
)

list(APPEND WebKitGLibAPITest_LIBRARIES
    WebKit::WPEToolingBackends
)

if (ENABLE_WPE_PLATFORM)
    add_subdirectory(WPEPlatform)
endif ()
