// RUN: %not %wgslc | %check

fn testIfDepth() {
    // CHECK-L: maximum parser recursive depth reached
    if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    } else if (true) {
    }
}
