/* ANSI-C code produced by gperf version 2.7.2 */
/* Command-line: gperf -L ANSI-C -E -C -n -o -t -k '*' -NfindValue -Hhash_val -Wwordlist_value -D cssvalues.gperf  */
/* This file is automatically generated from cssvalues.in by makevalues, do not edit */
/* Copyright 1999 W. Bastian */
#include "cssvalues.h"
struct css_value {
    const char *name;
    int id;
};
/* maximum key range = 1057, duplicates = 1 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_val (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057,    0, 1057, 1057,    0,   25,
        30,   35,   40,   50,    5,   10,   15,    0, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057,    0,   95,   10,
        85,   35,   10,   64,  158,   25,   10,  114,    0,   29,
        49,    0,   95,  155,   20,  240,    0,   24,  210,   28,
        93,    5,   50, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057, 1057,
      1057, 1057, 1057, 1057, 1057, 1057
    };
  register int hval = 0;

  switch (len)
    {
      default:
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
const struct css_value *
findValue (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 180,
      MIN_WORD_LENGTH = 3,
      MAX_WORD_LENGTH = 21,
      MIN_HASH_VALUE = 0,
      MAX_HASH_VALUE = 1056
    };

  static const struct css_value wordlist_value[] =
    {
      {"900", CSS_VAL_900},
      {"600", CSS_VAL_600},
      {"700", CSS_VAL_700},
      {"800", CSS_VAL_800},
      {"ltr", CSS_VAL_LTR},
      {"rtl", CSS_VAL_RTL},
      {"auto", CSS_VAL_AUTO},
      {"100", CSS_VAL_100},
      {"200", CSS_VAL_200},
      {"300", CSS_VAL_300},
      {"400", CSS_VAL_400},
      {"left", CSS_VAL_LEFT},
      {"500", CSS_VAL_500},
      {"wait", CSS_VAL_WAIT},
      {"italic", CSS_VAL_ITALIC},
      {"lower", CSS_VAL_LOWER},
      {"icon", CSS_VAL_ICON},
      {"top", CSS_VAL_TOP},
      {"normal", CSS_VAL_NORMAL},
      {"circle", CSS_VAL_CIRCLE},
      {"loud", CSS_VAL_LOUD},
      {"large", CSS_VAL_LARGE},
      {"bottom", CSS_VAL_BOTTOM},
      {"crop", CSS_VAL_CROP},
      {"text", CSS_VAL_TEXT},
      {"table", CSS_VAL_TABLE},
      {"none", CSS_VAL_NONE},
      {"menu", CSS_VAL_MENU},
      {"larger", CSS_VAL_LARGER},
      {"compact", CSS_VAL_COMPACT},
      {"mix", CSS_VAL_MIX},
      {"center", CSS_VAL_CENTER},
      {"pre", CSS_VAL_PRE},
      {"default", CSS_VAL_DEFAULT},
      {"lower-latin", CSS_VAL_LOWER_LATIN},
      {"below", CSS_VAL_BELOW},
      {"portrait", CSS_VAL_PORTRAIT},
      {"run-in", CSS_VAL_RUN_IN},
      {"narrower", CSS_VAL_NARROWER},
      {"table-cell", CSS_VAL_TABLE_CELL},
      {"table-row", CSS_VAL_TABLE_ROW},
      {"caption", CSS_VAL_CAPTION},
      {"bold", CSS_VAL_BOLD},
      {"lower-roman", CSS_VAL_LOWER_ROMAN},
      {"inline", CSS_VAL_INLINE},
      {"decimal", CSS_VAL_DECIMAL},
      {"repeat", CSS_VAL_REPEAT},
      {"repeat-y", CSS_VAL_REPEAT_Y},
      {"nowrap", CSS_VAL_NOWRAP},
      {"wider", CSS_VAL_WIDER},
      {"dotted", CSS_VAL_DOTTED},
      {"armenian", CSS_VAL_ARMENIAN},
      {"x-large", CSS_VAL_X_LARGE},
      {"marker", CSS_VAL_MARKER},
      {"block", CSS_VAL_BLOCK},
      {"text-top", CSS_VAL_TEXT_TOP},
      {"pointer", CSS_VAL_POINTER},
      {"medium", CSS_VAL_MEDIUM},
      {"ridge", CSS_VAL_RIDGE},
      {"thin", CSS_VAL_THIN},
      {"no-repeat", CSS_VAL_NO_REPEAT},
      {"bolder", CSS_VAL_BOLDER},
      {"double", CSS_VAL_DOUBLE},
      {"capitalize", CSS_VAL_CAPITALIZE},
      {"table-column", CSS_VAL_TABLE_COLUMN},
      {"fixed", CSS_VAL_FIXED},
      {"text-bottom", CSS_VAL_TEXT_BOTTOM},
      {"both", CSS_VAL_BOTH},
      {"georgian", CSS_VAL_GEORGIAN},
      {"middle", CSS_VAL_MIDDLE},
      {"right", CSS_VAL_RIGHT},
      {"small", CSS_VAL_SMALL},
      {"scroll", CSS_VAL_SCROLL},
      {"always", CSS_VAL_ALWAYS},
      {"move", CSS_VAL_MOVE},
      {"static", CSS_VAL_STATIC},
      {"katakana", CSS_VAL_KATAKANA},
      {"repeat-x", CSS_VAL_REPEAT_X},
      {"embed", CSS_VAL_EMBED},
      {"level", CSS_VAL_LEVEL},
      {"blink", CSS_VAL_BLINK},
      {"help", CSS_VAL_HELP},
      {"hand", CSS_VAL_HAND},
      {"outset", CSS_VAL_OUTSET},
      {"lighter", CSS_VAL_LIGHTER},
      {"hide", CSS_VAL_HIDE},
      {"fantasy", CSS_VAL_FANTASY},
      {"xx-large", CSS_VAL_XX_LARGE},
      {"thick", CSS_VAL_THICK},
      {"table-caption", CSS_VAL_TABLE_CAPTION},
      {"inherit", CSS_VAL_INHERIT},
      {"inline-table", CSS_VAL_INLINE_TABLE},
      {"justify", CSS_VAL_JUSTIFY},
      {"hiragana", CSS_VAL_HIRAGANA},
      {"avoid", CSS_VAL_AVOID},
      {"underline", CSS_VAL_UNDERLINE},
      {"smaller", CSS_VAL_SMALLER},
      {"relative", CSS_VAL_RELATIVE},
      {"groove", CSS_VAL_GROOVE},
      {"serif", CSS_VAL_SERIF},
      {"oblique", CSS_VAL_OBLIQUE},
      {"lower-alpha", CSS_VAL_LOWER_ALPHA},
      {"invert", CSS_VAL_INVERT},
      {"above", CSS_VAL_ABOVE},
      {"upper-latin", CSS_VAL_UPPER_LATIN},
      {"inset", CSS_VAL_INSET},
      {"solid", CSS_VAL_SOLID},
      {"lower-greek", CSS_VAL_LOWER_GREEK},
      {"list-item", CSS_VAL_LIST_ITEM},
      {"sub", CSS_VAL_SUB},
      {"disc", CSS_VAL_DISC},
      {"x-small", CSS_VAL_X_SMALL},
      {"upper-roman", CSS_VAL_UPPER_ROMAN},
      {"lowercase", CSS_VAL_LOWERCASE},
      {"hebrew", CSS_VAL_HEBREW},
      {"overline", CSS_VAL_OVERLINE},
      {"collapse", CSS_VAL_COLLAPSE},
      {"table-row-group", CSS_VAL_TABLE_ROW_GROUP},
      {"open-quote", CSS_VAL_OPEN_QUOTE},
      {"absolute", CSS_VAL_ABSOLUTE},
      {"table-footer-group", CSS_VAL_TABLE_FOOTER_GROUP},
      {"outside", CSS_VAL_OUTSIDE},
      {"super", CSS_VAL_SUPER},
      {"-konq-normal", CSS_VAL__KONQ_NORMAL},
      {"-konq-ruler", CSS_VAL__KONQ_RULER},
      {"separate", CSS_VAL_SEPARATE},
      {"show", CSS_VAL_SHOW},
      {"w-resize", CSS_VAL_W_RESIZE},
      {"hidden", CSS_VAL_HIDDEN},
      {"e-resize", CSS_VAL_E_RESIZE},
      {"no-open-quote", CSS_VAL_NO_OPEN_QUOTE},
      {"table-column-group", CSS_VAL_TABLE_COLUMN_GROUP},
      {"small-caption", CSS_VAL_SMALL_CAPTION},
      {"n-resize", CSS_VAL_N_RESIZE},
      {"xx-small", CSS_VAL_XX_SMALL},
      {"monospace", CSS_VAL_MONOSPACE},
      {"inside", CSS_VAL_INSIDE},
      {"higher", CSS_VAL_HIGHER},
      {"-konq-center", CSS_VAL__KONQ_CENTER},
      {"square", CSS_VAL_SQUARE},
      {"expanded", CSS_VAL_EXPANDED},
      {"baseline", CSS_VAL_BASELINE},
      {"katakana-iroha", CSS_VAL_KATAKANA_IROHA},
      {"nw-resize", CSS_VAL_NW_RESIZE},
      {"ne-resize", CSS_VAL_NE_RESIZE},
      {"close-quote", CSS_VAL_CLOSE_QUOTE},
      {"transparent", CSS_VAL_TRANSPARENT},
      {"cross", CSS_VAL_CROSS},
      {"landscape", CSS_VAL_LANDSCAPE},
      {"hiragana-iroha", CSS_VAL_HIRAGANA_IROHA},
      {"ultra-expanded", CSS_VAL_ULTRA_EXPANDED},
      {"upper-alpha", CSS_VAL_UPPER_ALPHA},
      {"line-through", CSS_VAL_LINE_THROUGH},
      {"decimal-leading-zero", CSS_VAL_DECIMAL_LEADING_ZERO},
      {"no-close-quote", CSS_VAL_NO_CLOSE_QUOTE},
      {"uppercase", CSS_VAL_UPPERCASE},
      {"cursive", CSS_VAL_CURSIVE},
      {"condensed", CSS_VAL_CONDENSED},
      {"dashed", CSS_VAL_DASHED},
      {"small-caps", CSS_VAL_SMALL_CAPS},
      {"status-bar", CSS_VAL_STATUS_BAR},
      {"extra-expanded", CSS_VAL_EXTRA_EXPANDED},
      {"visible", CSS_VAL_VISIBLE},
      {"ultra-condensed", CSS_VAL_ULTRA_CONDENSED},
      {"s-resize", CSS_VAL_S_RESIZE},
      {"cjk-ideographic", CSS_VAL_CJK_IDEOGRAPHIC},
      {"bidi-override", CSS_VAL_BIDI_OVERRIDE},
      {"table-header-group", CSS_VAL_TABLE_HEADER_GROUP},
      {"sw-resize", CSS_VAL_SW_RESIZE},
      {"se-resize", CSS_VAL_SE_RESIZE},
      {"static-position", CSS_VAL_STATIC_POSITION},
      {"crosshair", CSS_VAL_CROSSHAIR},
      {"-konq-xxx-large", CSS_VAL__KONQ_XXX_LARGE},
      {"extra-condensed", CSS_VAL_EXTRA_CONDENSED},
      {"-konq-around-floats", CSS_VAL__KONQ_AROUND_FLOATS},
      {"semi-expanded", CSS_VAL_SEMI_EXPANDED},
      {"message-box", CSS_VAL_MESSAGE_BOX},
      {"sans-serif", CSS_VAL_SANS_SERIF},
      {"semi-condensed", CSS_VAL_SEMI_CONDENSED},
      {"-konq-baseline-middle", CSS_VAL__KONQ_BASELINE_MIDDLE}
    };

  static const short lookup[] =
    {
         0,   -1,   -1,   -1,   -1,    1,   -1,   -1,
        -1,   -1,    2,   -1,   -1,   -1,   -1,    3,
        -1,   -1,   -1,   -1, -202, -176,   -2,   -1,
         6,    7,   -1,   -1,   -1,   -1,    8,   -1,
        -1,   -1,   -1,    9,   -1,   -1,   -1,   -1,
        10,   -1,   -1,   -1,   -1,   11,   -1,   -1,
        -1,   -1,   12,   -1,   -1,   13,   -1,   -1,
        -1,   -1,   -1,   -1,   14,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   15,   16,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   17,
        -1,   -1,   18,   -1,   19,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   20,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   21,
        -1,   -1,   -1,   -1,   22,   23,   -1,   -1,
        24,   -1,   25,   -1,   -1,   26,   -1,   -1,
        -1,   27,   -1,   28,   -1,   -1,   -1,   -1,
        29,   -1,   -1,   30,   -1,   31,   32,   -1,
        -1,   -1,   33,   -1,   -1,   34,   35,   -1,
        36,   -1,   -1,   -1,   -1,   -1,   -1,   37,
        -1,   -1,   -1,   -1,   38,   -1,   -1,   39,
        -1,   -1,   40,   41,   42,   43,   -1,   44,
        45,   46,   -1,   -1,   -1,   -1,   47,   -1,
        48,   49,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   50,   -1,   51,
        -1,   -1,   -1,   -1,   52,   -1,   -1,   -1,
        -1,   -1,   53,   54,   -1,   -1,   -1,   55,
        56,   -1,   -1,   57,   -1,   58,   -1,   -1,
        59,   -1,   60,   61,   -1,   -1,   -1,   62,
        63,   -1,   64,   -1,   -1,   -1,   -1,   -1,
        65,   -1,   -1,   -1,   66,   67,   -1,   -1,
        -1,   68,   -1,   69,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   70,   -1,   71,   72,   -1,
        -1,   73,   74,   75,   -1,   76,   77,   78,
        79,   -1,   -1,   80,   -1,   -1,   -1,   -1,
        81,   -1,   -1,   -1,   82,   -1,   -1,   -1,
        -1,   -1,   -1,   83,   -1,   -1,   84,   85,
        86,   87,   -1,   88,   -1,   89,   -1,   -1,
        90,   91,   92,   -1,   93,   -1,   -1,   -1,
        94,   -1,   95,   -1,   96,   97,   -1,   -1,
        -1,   98,   99,   -1,   -1,   -1,  100,   -1,
       101,   -1,   -1,  102,  103,   -1,   -1,  104,
        -1,   -1,   -1,   -1,   -1,  105,  106,  107,
        -1,   -1,  108,   -1,   -1,   -1,   -1,  109,
       110,   -1,  111,   -1,   -1,   -1,   -1,  112,
       113,   -1,   -1,  114,   -1,   -1,  115,   -1,
        -1,   -1,   -1,   -1,  116,  117,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,  118,  119,   -1,   -1,   -1,  120,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,  121,   -1,   -1,   -1,   -1,  122,   -1,
       123,  124,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,  125,  126,   -1,   -1,   -1,   -1,   -1,
        -1,  127,   -1,   -1,   -1,  128,   -1,   -1,
       129,   -1,  130,   -1,   -1,  131,   -1,   -1,
       132,   -1,   -1,   -1,   -1,   -1,  133,  134,
        -1,   -1,  135,  136,  137,   -1,   -1,   -1,
        -1,   -1,   -1,  138,   -1,   -1,   -1,   -1,
        -1,   -1,  139,   -1,   -1,  140,   -1,  141,
       142,   -1,  143,   -1,   -1,   -1,   -1,   -1,
        -1,  144,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,  145,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  146,   -1,  147,   -1,
        -1,   -1,  148,   -1,   -1,   -1,   -1,  149,
        -1,  150,  151,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,  152,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,  153,  154,   -1,   -1,   -1,
        -1,   -1,  155,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  156,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  157,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,  158,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,  159,   -1,
        -1,   -1,   -1,  160,   -1,   -1,   -1,   -1,
        -1,  161,   -1,   -1,   -1,   -1,  162,   -1,
       163,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,  164,   -1,   -1,
        -1,   -1,   -1,  165,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  166,   -1,   -1,   -1,
        -1,   -1,  167,   -1,   -1,   -1,   -1,   -1,
        -1,  168,   -1,   -1,   -1,   -1,   -1,   -1,
       169,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,  170,   -1,   -1,
        -1,  171,   -1,   -1,  172,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
       173,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,  174,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,  175,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,  176,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,  177,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,  178,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
       179
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_val (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_value[index].name;

              if (*str == *s && !strcmp (str + 1, s + 1))
                return &wordlist_value[index];
            }
          else if (index < -TOTAL_KEYWORDS)
            {
              register int offset = - 1 - TOTAL_KEYWORDS - index;
              register const struct css_value *wordptr = &wordlist_value[TOTAL_KEYWORDS + lookup[offset]];
              register const struct css_value *wordendptr = wordptr + -lookup[offset + 1];

              while (wordptr < wordendptr)
                {
                  register const char *s = wordptr->name;

                  if (*str == *s && !strcmp (str + 1, s + 1))
                    return wordptr;
                  wordptr++;
                }
            }
        }
    }
  return 0;
}
static const char * valueList[] = {
"",
"inherit", 
"none", 
"hidden", 
"dotted", 
"dashed", 
"solid", 
"double", 
"groove", 
"ridge", 
"inset", 
"outset", 
"caption", 
"icon", 
"menu", 
"message-box", 
"small-caption", 
"status-bar", 
"italic", 
"oblique", 
"small-caps", 
"normal", 
"bold", 
"bolder", 
"lighter", 
"100", 
"200", 
"300", 
"400", 
"500", 
"600", 
"700", 
"800", 
"900", 
"xx-small", 
"x-small", 
"small", 
"medium", 
"large", 
"x-large", 
"xx-large", 
"-konq-xxx-large", 
"smaller", 
"larger", 
"wider", 
"narrower", 
"ultra-condensed", 
"extra-condensed", 
"condensed", 
"semi-condensed", 
"semi-expanded", 
"expanded", 
"extra-expanded", 
"ultra-expanded", 
"serif", 
"sans-serif", 
"cursive", 
"fantasy", 
"monospace", 
"transparent", 
"repeat", 
"repeat-x", 
"repeat-y", 
"no-repeat", 
"baseline", 
"middle", 
"sub", 
"super", 
"text-top", 
"text-bottom", 
"top", 
"bottom", 
"-konq-baseline-middle", 
"left", 
"right", 
"center", 
"justify", 
"-konq-center", 
"outside", 
"inside", 
"disc", 
"circle", 
"square", 
"decimal", 
"decimal-leading-zero", 
"lower-roman", 
"upper-roman", 
"lower-greek", 
"lower-alpha", 
"lower-latin", 
"upper-alpha", 
"upper-latin", 
"hebrew", 
"armenian", 
"georgian", 
"cjk-ideographic", 
"hiragana", 
"katakana", 
"hiragana-iroha", 
"katakana-iroha", 
"inline", 
"block", 
"list-item", 
"run-in", 
"compact", 
"marker", 
"-konq-ruler", 
"table", 
"inline-table", 
"table-row-group", 
"table-header-group", 
"table-footer-group", 
"table-row", 
"table-column-group", 
"table-column", 
"table-cell", 
"table-caption", 
"auto", 
"crosshair", 
"default", 
"pointer", 
"move", 
"e-resize", 
"ne-resize", 
"nw-resize", 
"n-resize", 
"se-resize", 
"sw-resize", 
"s-resize", 
"w-resize", 
"text", 
"wait", 
"help", 
"ltr", 
"rtl", 
"capitalize", 
"uppercase", 
"lowercase", 
"visible", 
"collapse", 
"above", 
"absolute", 
"always", 
"avoid", 
"below", 
"bidi-override", 
"blink", 
"both", 
"close-quote", 
"crop", 
"cross", 
"embed", 
"fixed", 
"hand", 
"hide", 
"higher", 
"invert", 
"landscape", 
"level", 
"line-through", 
"loud", 
"lower", 
"mix", 
"no-close-quote", 
"no-open-quote", 
"nowrap", 
"open-quote", 
"overline", 
"portrait", 
"pre", 
"relative", 
"scroll", 
"separate", 
"show", 
"static", 
"static-position", 
"thick", 
"thin", 
"underline", 
"-konq-normal", 
"-konq-around-floats", 
    0
};
DOMString getValueName(unsigned short id)
{
    if(id >= CSS_VAL_TOTAL || id == 0)
      return DOMString();
    else
      return DOMString(valueList[id]);
};

