/*
 * Copyright (C) 2006, 2009, 2010 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

[
    ExportMacro=WEBCORE_EXPORT,
    JSGenerateToNativeObject,
    ConstructorCallWith=Document,
    NamedConstructor=Image(optional unsigned long width, optional unsigned long height)
] interface HTMLImageElement : HTMLElement {
    [CEReactions=NotNeeded, Reflect] attribute DOMString name;
    [CEReactions=NotNeeded, Reflect] attribute DOMString align;
    [CEReactions=NotNeeded, Reflect] attribute DOMString alt;
    [CEReactions=NotNeeded, Reflect] attribute [TreatNullAs=EmptyString] DOMString border;
    [CEReactions=NotNeeded] attribute DOMString? crossOrigin;
    [CEReactions=NotNeeded] attribute unsigned long height;
    [CEReactions=NotNeeded, Reflect] attribute unsigned long hspace;
    [CEReactions=NotNeeded, Reflect] attribute boolean isMap;
    [CEReactions=NotNeeded, Reflect, URL] attribute USVString longDesc;
    [CEReactions=NotNeeded, Reflect, URL] attribute USVString src;
    [CEReactions=NotNeeded, Reflect] attribute USVString srcset;
    [CEReactions=NotNeeded, Reflect] attribute DOMString sizes;
    readonly attribute USVString currentSrc;
    [CEReactions=NotNeeded, Reflect] attribute DOMString useMap;
    [CEReactions=NotNeeded, Reflect] attribute unsigned long vspace;
    [CEReactions=NotNeeded] attribute unsigned long width;
    [CEReactions=NotNeeded, Reflect] attribute DOMString decoding;

    [Conditional=ATTACHMENT_ELEMENT, EnabledAtRuntime=AttachmentElement] readonly attribute DOMString attachmentIdentifier;

    [EnabledAtRuntime=ReferrerPolicyAttribute, ImplementedAs=referrerPolicyForBindings, CEReactions=NotNeeded] attribute DOMString referrerPolicy;
    [CEReactions, EnabledBySetting=LazyImageLoading, ImplementedAs=loadingForBindings] attribute DOMString loading;

    // Extensions
    readonly attribute boolean complete;
    [CEReactions=NotNeeded, Reflect, URL] attribute USVString lowsrc;
    readonly attribute long naturalHeight;
    readonly attribute long naturalWidth;
    readonly attribute long x;
    readonly attribute long y;

    Promise<undefined> decode();
};

