/*
 * Copyright (C) 2006, 2010 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 * Copyright (C) 2011 Motorola Mobility, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface HTMLTextAreaElement : HTMLElement {
        attribute [TreatNullAs=EmptyString] DOMString defaultValue;
        readonly attribute HTMLFormElement form;
        readonly attribute ValidityState validity;
        attribute long cols;
        attribute [Reflect] DOMString dirName;
        attribute [Reflect] boolean disabled;
        attribute [Reflect] boolean autofocus;
        attribute long maxLength setter raises(DOMException);
        attribute [TreatNullAs=EmptyString] DOMString name;
        attribute [Reflect] DOMString placeholder;
        attribute [Reflect] boolean readOnly;
        attribute [Reflect] boolean required;
        attribute long rows;
        attribute [Reflect] DOMString wrap;
        readonly attribute DOMString type;
        attribute [TreatNullAs=EmptyString] DOMString value;
        readonly attribute unsigned long textLength;

        void select();

        readonly attribute boolean willValidate;
        readonly attribute DOMString validationMessage;
        boolean checkValidity();
        void setCustomValidity(in [TreatNullAs=EmptyString, TreatUndefinedAs=EmptyString] DOMString error);

        // WinIE & FireFox extension:
        attribute long selectionStart;
        attribute long selectionEnd;
        attribute DOMString selectionDirection;
#if defined(LANGUAGE_OBJECTIVE_C) && LANGUAGE_OBJECTIVE_C
        void setSelectionRange(in long start, in long end);
#else
        void setSelectionRange(in [Optional=CallWithDefaultValue] long start, 
                               in [Optional=CallWithDefaultValue] long end, 
                               in [Optional] DOMString direction);
#endif
        readonly attribute NodeList labels;
    };

}
