/*
 * Copyright (C) 2006, 2007, 2009 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

[
    CustomConstructor(),
    ExportMacro=WEBCORE_EXPORT,
    JSCustomPushEventHandlerScope,
    JSGenerateToNativeObject,
] interface HTMLElement : Element {
    [CEReactions, Reflect] attribute DOMString title;
    [CEReactions, Reflect] attribute DOMString lang;
    [CEReactions] attribute boolean translate;
    [CEReactions] attribute DOMString dir;

    [CEReactions] attribute long tabIndex;
    [CEReactions] attribute boolean draggable;

    [CEReactions, Reflect] attribute DOMString webkitdropzone;
    // FIXME: Support the standard HTML equivalent.
    // [PutForwards=value] readonly attribute DOMTokenList dropzone;

    [CEReactions, Reflect] attribute boolean hidden;
    [CEReactions, Reflect] attribute DOMString accessKey;

    [CEReactions, SetterMayThrowException, TreatNullAs=EmptyString] attribute DOMString innerText;
    [CEReactions, SetterMayThrowException, TreatNullAs=EmptyString] attribute DOMString outerText;

    [CEReactions, SetterMayThrowException] attribute DOMString contentEditable;
    readonly attribute boolean isContentEditable;

    [CEReactions] attribute boolean spellcheck;

    [Conditional=IOS_AUTOCORRECT_AND_AUTOCAPITALIZE] attribute boolean autocorrect;
    [Conditional=IOS_AUTOCORRECT_AND_AUTOCAPITALIZE, TreatNullAs=EmptyString] attribute DOMString autocapitalize;

    void click();

    void focus();
    void blur();

    readonly attribute DOMStringMap dataset;
};

HTMLElement implements GlobalEventHandlers;
