/*
 * Copyright (C) 2006, 2009, 2010 Apple Inc. All rights reserved.
 * Copyright (C) 2006 Samuel Weinig <sam.weinig@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

module html {

    interface HTMLBodyElement : HTMLElement {
        attribute [Reflect] DOMString aLink;
        attribute [Reflect] DOMString background;
        attribute [Reflect] DOMString bgColor;
        attribute [Reflect] DOMString link;
        attribute [Reflect] DOMString text;
        attribute [Reflect] DOMString vLink;

#if !defined(LANGUAGE_OBJECTIVE_C) || !LANGUAGE_OBJECTIVE_C
        // Event handler attributes
        attribute [NotEnumerable, WindowEventListener] EventListener onbeforeunload;
        attribute [NotEnumerable, WindowEventListener] EventListener onhashchange;
        attribute [NotEnumerable, WindowEventListener] EventListener onmessage;
        attribute [NotEnumerable, WindowEventListener] EventListener onoffline;
        attribute [NotEnumerable, WindowEventListener] EventListener ononline;
        attribute [NotEnumerable, WindowEventListener] EventListener onpopstate;
        attribute [NotEnumerable, WindowEventListener] EventListener onresize;
        attribute [NotEnumerable, WindowEventListener] EventListener onstorage;
        attribute [NotEnumerable, WindowEventListener] EventListener onunload;

        attribute [Conditional=ORIENTATION_EVENTS, NotEnumerable, WindowEventListener] EventListener onorientationchange;

        // Overrides of Element attributes (with different implementation in bindings).
        attribute [NotEnumerable, WindowEventListener] EventListener onblur;
        attribute [NotEnumerable, WindowEventListener] EventListener onerror;
        attribute [NotEnumerable, WindowEventListener] EventListener onfocus;
        attribute [NotEnumerable, WindowEventListener] EventListener onload;

        // Not implemented yet.
        // attribute [NotEnumerable, WindowEventListener] EventListener onafterprint;
        // attribute [NotEnumerable, WindowEventListener] EventListener onbeforeprint;
        // attribute [NotEnumerable, WindowEventListener] EventListener onredo;
        // attribute [NotEnumerable, WindowEventListener] EventListener onundo;
#endif
    };

}
