#ifndef CMAKECONFIG_H
#define CMAKECONFIG_H

#define WEBKIT_USER_AGENT_MAJOR_VERSION @USER_AGENT_VERSION_MAJOR@
#define WEBKIT_USER_AGENT_MINOR_VERSION @USER_AGENT_VERSION_MINOR@

#define ENABLE_AS_IMAGE @ENABLE_AS_IMAGE_VALUE@
#define ENABLE_BLOB @ENABLE_BLOB_VALUE@
#define ENABLE_CHANNEL_MESSAGING @ENABLE_CHANNEL_MESSAGING_VALUE@
#define ENABLE_DATABASE @ENABLE_DATABASE_VALUE@
#define ENABLE_DATAGRID @ENABLE_DATAGRID_VALUE@
#define ENABLE_DATALIST @ENABLE_DATALIST_VALUE@
#define ENABLE_DATA_TRANSFER_ITEMS @ENABLE_DATA_TRANSFER_ITEMS_VALUE@
#define ENABLE_DOM_STORAGE @ENABLE_DOM_STORAGE_VALUE@
#define ENABLE_EVENTSOURCE @ENABLE_EVENTSOURCE_VALUE@
#define ENABLE_FAST_MOBILE_SCROLLING @ENABLE_FAST_MOBILE_SCROLLING_VALUE@
#define ENABLE_FILTERS @ENABLE_FILTERS_VALUE@
#define ENABLE_FTPDIR @ENABLE_FTPDIR_VALUE@
#define ENABLE_GEOLOCATION @ENABLE_GEOLOCATION_VALUE@
#define ENABLE_GLIB_SUPPORT @ENABLE_GLIB_SUPPORT_VALUE@
#define ENABLE_ICONDATABASE @ENABLE_ICONDATABASE_VALUE@
#define ENABLE_INSPECTOR @ENABLE_INSPECTOR_VALUE@
#define ENABLE_JAVASCRIPT_DEBUGGER @ENABLE_JAVASCRIPT_DEBUGGER_VALUE@
#define ENABLE_JIT @ENABLE_JIT_VALUE@
#define ENABLE_MATHML @ENABLE_MATHML_VALUE@
#define ENABLE_NETSCAPE_PLUGIN_API @ENABLE_NETSCAPE_PLUGIN_API_VALUE@
#define ENABLE_NOTIFICATIONS @ENABLE_NOTIFICATIONS_VALUE@
#define ENABLE_OFFLINE_WEB_APPLICATIONS @ENABLE_OFFLINE_WEB_APPLICATIONS_VALUE@
#define ENABLE_ORIENTATION_EVENTS @ENABLE_ORIENTATION_EVENTS_VALUE@
#define ENABLE_PROGRESS_TAG @ENABLE_PROGRESS_TAG_VALUE@
#define ENABLE_SHARED_WORKERS @ENABLE_SHARED_WORKERS_VALUE@
#define ENABLE_SVG @ENABLE_SVG_VALUE@
#define ENABLE_SVG_ANIMATION @ENABLE_SVG_ANIMATION_VALUE@
#define ENABLE_SVG_FONTS @ENABLE_SVG_FONTS_VALUE@
#define ENABLE_SVG_FOREIGN_OBJECT @ENABLE_SVG_FOREIGN_OBJECT_VALUE@
#define ENABLE_SVG_USE @ENABLE_SVG_USE_VALUE@
#define ENABLE_TOUCH_EVENTS @ENABLE_TOUCH_EVENTS_VALUE@
#define ENABLE_VIDEO @ENABLE_VIDEO_VALUE@
#define ENABLE_WEB_SOCKETS @ENABLE_WEB_SOCKETS_VALUE@
#define ENABLE_WORKERS @ENABLE_WORKERS_VALUE@
#define ENABLE_XHTMLMP @ENABLE_XHTMLMP_VALUE@
#define ENABLE_XPATH @ENABLE_XPATH_VALUE@
#define ENABLE_XSLT @ENABLE_XSLT_VALUE@

#endif /* CMAKECONFIG_H */
